---
title: "lee"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
```

```{r}
text <- readLines("~/scrapy/ralady/sources/lee.txt")
#head(text, 50)
nos <- grep("^[^0-9“”]",text)#remove lines that don't start with numbers
if(length(nos)>0){
  text <- text[-nos]
}
qs <- grep("^“",text)
for(i in 1:length(qs)){
  prev <- qs[i]-1
  text[prev] <- paste(text[prev],text[qs[i]])
}
text <- text[-qs]
#head(text, 50)
ls <- grep("“",text)
newtext<- vector(mode="character", length=length(ls))
for(i in 1:length(ls)){
  newtext[i] <- text[ls[i]]
}
#head(newtext, 50)
cites <- grep("\\(.*[0-9][0-9][0-9][0-9].*\\)",newtext)
munro <- grep("\\(.*Munro",newtext)
nmcites <- setdiff(cites,munro)
newtext <- newtext[-nmcites]
secs <- grep("^[0-9]+\\.[0-9]+",newtext)
newtext <- newtext[-secs]
secs2 <- grep("^[0-9]+ [aA-zZ]",newtext)
newtext <- newtext[-secs2]
ungrammatical <- grep("\\*",newtext)
newtext <- newtext[-ungrammatical]
infelicitious <- grep("\\#",newtext)
newtext <- newtext[-infelicitious]
head(newtext,15)
splitt <- data.frame(Zap= character(0), Gloss=character(0), Trans=character(0),stringsAsFactors=FALSE)
for(i in 1:length(newtext)){
  t <- newtext[i]
  t <- stringr::str_replace_all(t,"[0-9]*\\.", "")
  lines <- stringr::str_split(t, "“")
  lines[[1]] <-  stringr::str_replace_all(lines[[1]],"[\",”]","")
  trans <- lines[[1]][[2]]
  z <- stringr::str_split(lines[[1]][[1]]," ")
  indexes <- which(z == "")
  if(length(indexes)>0){
    z <- z[-indexes]
  }
  sep <- stringr::str_split(z, " ")
  length <- length(sep[[1]])
  half <- length/2
  zap <- paste0(sep[[1]][-(half+1:length)],collapse = " ")
  gloss <- paste0(sep[[1]][-(1:half)],collapse = " ")
  splitt[i,] <- rbind(zap,gloss,trans)
}
```