D e s d e   a n s t e   n i   g u r i x t i   g u ɨ c h l i u   a g a c   n u u   t u b y   n i   l á   D i i d x   .   L a a n y   r b e z n é n y   D i o s   n e   l a a z a c n y   n á n y   D i o s   .  
N i   l á   D i i d x q u i   a g a c   r b e z n é n y   D i o s   c h i   g u z u l o   g u r i x t i   g u ɨ c h l i u   .  
I r a t e   d e   n i   n u u   ,   p u r   l a a n y   g u c c h u u d e n i   .   X í t e e t e   q u ɨ t   x i   n u u t i   n i   q u ɨ t   g u c   p u r   l a a n y   .  
N e   l a a n y   n a p n y   g u e l n a b á n y   .   C h i y   g u e l n a b á n y q u i   n á   b i e e n y   p a r   i r a t e   b ɨ n g u ɨ c h l i u   .  
N e   b i e e n q u i   r z i e e n n y   x q u e l r i e n y   d e   b n i e t y   a x   m á s   ,   m á s   n a c a y   x q u e l r i e n d e b   ,   p e r   q u ɨ t   x o   s u t i   g u e l n a c a y q u i   l o   b i e e n y   x t e   D i o s   .  
G u u   t u b y   b n i e t y   n i   b d i a l á   J u a n y   .   L a a b   n á   n i   b c u a b e e   D i o s
p a r   g u c b ɨ   z e c   t u b y   t e s t i g u   .   B e d g ü e e b   d i i d x   p u r   x p i e e n y   D i o s   t e   p a r   c h a l e e   c h a l d i l a a z   i r a   b n i e t n y   .  
P e r   g a t i   l a g a c t i   J u a n y   g u c   x p i e e n y   D i o s   s i n o   q u e   l a a b   b e e d t i s b ɨ   p a r   g u d i x t e e b   l o   d e   b n i e t y   x a   n á   b i e e n q u i   .  
T e   p u r   n i   n á   m e r p a c   b i e e n q u i   l a a n y   r z i e e n n y   x q u e l r i e n y   i r a   b n i e t y   g u ɨ c h l i u   n e   a b e e d n y   l o   g u ɨ c h l i u   .  
L a a n y   g u z u g u a a n y   l o   g u ɨ c h l i u   ,   n e   m a s q u ɨ   p u r   l a a n y   n u u   g u ɨ c h l i u   ,   p e r   d e   b n i e t y   g u ɨ c h l i u   q u ɨ t   n i z i g u e l d t i   n i u m b e e   l a a n y   z e c   n i   n á   p a r   n i u m b e e d e b n y   .  
B d z ɨ n n y   l o   g u ɨ c h l i u   l o   n a c i o n y   I s r a e l   n e   m a s q u ɨ   g u c n y   b n i e t y   I s r a e l   ,   p e r   d e   b n i e t y   I s r a e l   q u ɨ t   b a a n t i d e b   c u e n d   x t i i d x n y   .  
P e r   m a s q u ɨ   z i y   ,   i r a t e   d e   n i   b a a n y   c u e n d   l a a n y   n e   g ü e l d i l a a z d e b n y   ,   b d e e d n y   l a a d e b   g u e l r n a b e e   p a r   g a c d e b   d e   l l i i n   D i o s   .  
N e   m a s q u ɨ   l l i i n   b n i e t y   g u ɨ c h l i u   r a c   b n i e t y   o   m a s q u ɨ z a   p u r   x g a b   b n i e t y   o   p u r   z é e d   g a n   g a p   b n i e t y   l l i i n n i   l o   g u ɨ c h l i u r é   ,   p e r   g a t i   p u r   z i y t i   a   n á   b n i e t y   l l i i n   D i o s   s i n o   q u e   p u r   g u e l r e l d i l a a z   a n á d e b   l l i i n   D i o s   .  
D i i d x   n i   g u l e z n é   D i o s   d e s d ɨ   g u l o   ,   l a a n y   g u c n y   b n i e t y   .   G u b á n n y   l o   g u ɨ c h l i u   c u n   d u n n ɨ   ,   n e   g a t i   g u l l i e e z t i   n á   g u e l r c a a z   x t e n n y   a x   p ú r p a c   d i d x l d í   g u n i i n y   .   (   D u n n ɨ   g u n á n   g u e l r n a b e e   x t e n n y   ,   g u e l r n a b e e   n i   c u á a n y   p u r   l a a t i s n y   n á n y   L l i i n p a c   D i o s   .   )  
C h i   b e n é   J u a n y   d e   b n i e t y   x t i i d x n y   ,   l a a b   g u n i i b   :   —   J e s ú s r e n i y   n á   n i   r z e e t a   c h i   g u n i i a   l a a t   d e c   n i   g u e e d   d e s p u é s   d e   n a r e   l a a n y   m a z r u   s a c n y   q u e   n a a   t e   p u r   a g a c   g u l a l   n u u n y   q u e   n a r e   .  
P u r   l a a n y   i r a t e c n ɨ   a r d x a p n ɨ   g u e l n a b á n y   z e c t i s p a c   l a a n y   ,   n e   d x i   p u r   d x i   c a y u n l d e e n y   q u i a n   .  
P u r   M o i s é s   b n ɨ ɨ d x   D i o s   d u n n ɨ   l e y   x t e n n y   ,   p e r   p u r   J e s u c r i s t   g u c b e e l d í n   x a   n á   g u e l r c a a z   n e   d i d x l d í   x t e n n y   .  
G a d y   c h ú u t i   d x i   i n i á   b n i e t y   D i o s   ,   q u e s o l t i s y   t u b y z i   L l i i n n y   n i   r b e z n é   l a a n y   a b l i u u   d u n n ɨ   x a   n á   D i o s   .   (   M t   .   3   :   1   1   ‑   1   2   ;   M r   .   1   :   7   ‑   8   ;   L c   .   3   :   1   5   ‑   1   7   )  
C h i y   d e s d e   J e r u s a l é n   d e   g u r t i s y   x t e   d e   b n i e t y   I s r a e l   b x i a a l d d e b   d e   b x o z   c u n   d e   b ɨ n y   l e v i t a s   p a r   g ü e n a b d i i d x d e b   J u a n y   t ú   n á b   .   C h i y r u   b e n é   J u a n y   l a a d e b   d i i d x   .  
B z i r u u b   i r a i r a t e   l o d e b   r a i p b ɨ   l a a d e b   :   —   G a t i   n a r e t i a   n a a   C r i s t   .  
C h i y   g u b í i   g u n a b d i i d x d e b   l a a b   :   —   ¿ T ú z a   l i ú   d x a   ?   ¿ T a   l i ú y   E l í a s   ?   J u a n y   c u a i b b ɨ   :   —   G a t i   n a r e t i a y   .   C h i y r u   r a i p d e b   l a a b   :   —   O   ,   ¿ t a   l i ú y   p r o f e t   n i   n á   p a r   g u e e d   ?   L a a b   c u a i b b ɨ   :   —   G a t i   n a r e t i a y   .  
C h i y   r a i p d e b   l a a b   :   —   ¿ T ú z a   l i ú   ,   p ɨ s   ?   T e   p u r   n á   p a r   c h o n é n   r s o n   l o   d e   n i   b x i a a l d   d u n n ɨ   .   G u n i i   d u n n ɨ   t ú   l i ú   .  
C h i y r u   r a i p y   J u a n y   l a a d e b   :   —   N a r e   n a a   t u b y   n i   r b ɨ x t i a   n e z   l o   y i u b i z   r u t   q u ɨ t   t u   r b e z t i   :   “   G u l g a a n y   t u b y   l d í   n e z   p a r   X t a d n ɨ   n i   r n a b e e ”   ,   z e c   n i   g u n i i   p r o f e t   I s a í a s   d e s d ɨ   g u l a l   .  
C h i y r u   d e   b ɨ n y   n i   b x i a a l d   d e   f a r i s e u   p a r   i n i n é d e b   J u a n y   ,  
g u n a b d i i d x d e b   l a a b   :   —   B e l a t i   g a t i   l i ú   n o o   C r i s t   n i c z a   E l í a s   ,   n i c z a   p r o f e t   n i   n á   p a r   g u e e d   ,   ¿ x i z a n i   r t i u b n i s u   b n i e t y   p ɨ s   ?  
J u a n y   a x   c u a i b b ɨ   l o d e b   :   —   N a r e   r t i u b n i s a   c u n   n i s   .   P e r   l o t   n u u   t u b y   b n i e t y   n i   g a d y   g u m b e e t i t   .  
N e   l a a n i y   n á   p a r   g u e e d   d e s p u é s   d e   n a r e   ,   a x   n i c l ɨ   l o   x c u r a c h n y   q u ɨ t   r i á l d t i   i x a i c q u i a   t e   p u r   m a z r u   s a c n y   q u e   n a r e   .  
I r a t e   d e   c o s r é   g u c   n e z   r u t   l á   B e t á b a r a   ,   n i   n á   s t u b y   l a d   r u u   g u e e u   J o r d á n   r u t   b t i u b n i s   J u a n y   d e   b n i e t y   .  
C h i   b r a g u e e l   s t u b y   d x i   ,   J u a n y   g u n á b   d e c   z e d z ɨ n g a x   J e s ú s   r u t   z u g u a a b   ,   a x   g u n i i b   :   —   G u l g u i a a   .   B n i e t r e n i y   a b c u a b e e   D i o s   p a r   g a t y n y   z e c   t u b y   C o r d e r   p u r   d e   x t u l d   b n i e t y   g u ɨ c h l i u   .  
L a a n i y   r z e e t a   c h i   g u n i i a   l a a t   :   “   D e s p u é s   d e   n a r e   g u e e d   t u b y   b n i e t y   n i   m a z r u   s a c   q u e   n a a   ,   t e   p u r   l a a n y   a g a c   g u l a l   n u u n y   q u e   n a a   .   ”
N e   n i c l ɨ   n a r e   q u ɨ t   g u c b e e t i a   d e c   l a a n i y   n á   p a r   g u e e d n y   ,   p e r   n a r e   z e l d a   p a r   c a t i u b n i s a   d e   b n i e t y   c u n   n i s   p a r   c h a l e e   g u m b e e   d e   b n i e t y   I s r a e l   l a a n y   .  
Z i y z a   r a i p y   J u a n y   l a a d e b   :   —   N a r e   g u n á a   b i a t   S p í r i t u   S a n t   l l a y a b a a   z e c   t u b y   p a l o m   a x t q u ɨ   q u i a n y   .  
M a s q u ɨ   q u ɨ t   r u m b e e t i a n y   ,   p e r   n i   b x i a a l d   n a r e   p a r   i t i u b n i s a   c u n   n i s   l a a n y   g u n i i n y   n a r e   :   “   C h i   i n i o o   y i a t   S p í r i t u   S a n t   a x t   q u i a   t u b y   b n i e t y   ,   l a a n i y   n á   n i   r t i u b n i s n y   b n i e t y   c u n   S p í r i t u   S a n t   .   ”
N a r e   a g u n á a n y   ,   n e   n a n l d í z a c a   d e c   l a a n y   n á n y   L l i i n   D i o s   .  
C h i   b r a g u e e l   s t u b y   d x i   d e n i   z u g u a n é   J u a n y   t i o p   d e   x p ɨ n b ɨ   ,  
c h i   g u n á b   z e t e e d   J e s ú s   ,   a x   g u n i i b   :   —   G u l g u i a a   .   B n i e t r e n i y   a b c u a b e e   D i o s   p a r   g a t y n y   z e c   t u b y   C o r d e r   .  
C h i   b i n d i a g   i r o p t e   d e   x p ɨ n b ɨ   z i y   ,   a x   g u z a n a l d d e b   J e s ú s   .  
D e n i   b z i e c q u i l o   J e s ú s   ,   c h i   g u n á n y   z a n a l d d e b   l a a n y   ,   a x   r a i p n y   l a a d e b   :   —   ¿ X i   r g u í i l y t ɨ   ?   L a a d e b   a x   c u a i b d e b   :   —   M a i s t r ɨ   ,   ¿ c a l í   r b e z b i u   ?  
C h i y r u   r a i p y   J e s ú s   l a a d e b   :   —   G u l t a a   t e   í g u i a a t   .   C h i y r u   g ü e d e b   p a r   g u n á d e b   c a l í   r b e z n y   ,   a x   b i a n n é d e b n y   d x i q u i   ,   t e   p u r   z e c t i   r c a   t a p   g u d x i y   .  
T u b y   d e   x p ɨ n y   J u a n y   n i   g ü e n a l d   J e s ú s   ,   p u r   n i   b i n d i a g b ɨ   n i   g u n i i   J u a n y   ,   l a a b   b d i a l á b   A n d r é s   b e t s   S i m ó n y   B e d   .  
A n d r é s q u i   n i d o n i d o o t e   b e t s b ɨ   S i m ó n y   g ü e t í i l y b ɨ   a x   r a i p b ɨ   l a a b   :   —   A b d x i a l n ɨ   M e s í a s   (   z e l o   d i i d x q u i   ,   C r i s t   )   .  
C h i y r u   g ü e n é   A n d r é s   S i m ó n y   r u t   z u g u a a   J e s ú s   c h i y   c h i   g u n á   J e s ú s   l a a b   a x   g u n i i n y   :   —   L i ú y   S i m ó n y   ,   l l i n g a a n   J o n á s   ,   p e r   a n r e   i d i a l o o   C e f a s   (   z e l o   d i i d x q u i   ,   B e d   )   .  
C h i   b r a g u e e l   s t u b y   d x i   J e s ú s   b a a n n y   x g a b   c h i a n y   n e z   G a l i l e a   a x   b d x á a n y   L i b y   .   C h i y   r a i p n y   l a a b   :   —   Q u e d a n a l d   n a r e   .  
L i b y r é   g u ɨ d x   B e t s a i d a   n á   l a d x b ɨ   r u t   z á   B e d   c u n   A n d r é s   .  
C h i y r u   g ü e t í i l y   L i b y   N a t a n a e l   ,   a x   r a i p b ɨ   l a a b   :   —   A b d x i a l n ɨ   b n i e t y   n i   r z e e t   M o i s é s   l o   l i b r ɨ   x t e   l e y   ,   n e   l a a z a c n i y   n i   r z e e t   d e   p r o f e t   n i   b c u a a   x t i i d x   D i o s   .   L a a n i y   J e s ú s   l l i n g a a n   G u s é   n i   z á   g u ɨ d x   N a z a r e t   .  
C h i y   c u a b y   N a t a n a e l   :   —   ¿ T a t i x   n u u   b n i e t y   N a z a r e t   n i   n á   g ü e n   ?   C h i y r u   r a i p y   L i b y   l a a b   :   —   E d a g u i a a   c a n i o o   .  
C h i   g u n á   J e s ú s   z é e d   N a t a n a e l   ,   a x   g u n i i n y   :   —   R u r é n   z é e d   t u b y   b n i e t y   n i   n á   m e r p a c   b n i e t y   I s r a e l   .   N e   q u ɨ t   x i   e n g a n y t i   r u n b ɨ   b n i e t y   .  
C h i y r u   g u n a b d i i d x   N a t a n a e l   l a a n y   :   —   ¿ X o   r u m b e e b i u   n a r e   ?   J e s ú s   a x   c u a i b n y   :   —   A n s t e   n i   c u i d x   L i b y   l i ú   ,   c h i   z u g o o   l l a a   y a g   h i g   ,   c h i y   g u n á a   l i ú   .  
C h i y   r a i p y   N a t a n a e l   l a a n y   :   —   M a i s t r ɨ   ,   l a a b i u   n á b i u   L l i i n   D i o s   .   L a a b i u   n á b i u   R e y   x t e   I s r a e l   .  
C h i y r u   a x   c u a b y   J e s ú s   l o b   :   —   L i ú   r e l d i l a a z u   n a r e   p u r z i   n i   g u n i i a   l i ú   d e c   g u n á a   l i ú   l l a a   y a g   h i g   .   P e r   t e r u   m a z r u   n i   i n i o o   q u e   n i   a g u n o o   .  
Z i y z a   r a i p y   J e s ú s   l a a b   :   —   N a r e   n a n c h u u a   d e c   l a a t   s n i á t   z u l l a l   l l a y a b a a   n e   s n i á z a c t ɨ   d e   á n g l ɨ   x t e   D i o s   r i e e p d e b   l l a y a b a a   n e   r i a t z a d e b   a x t   q u i a   B n i e t y   n i   b x i a a l d   D i o s   l o   g u ɨ c h l i u   .  
N i   r i o n   d x i   ,   a x   g u u   t u b y   s a a   l á a n i   g u ɨ d x   C a n á   n i   n á   n e z   G a l i l e a   .   C h i y   n é   x n a n   J e s ú s   z u g u a a   r u y   ,  
n e   n é z a   J e s ú s   c u n   d e   x p ɨ n n y   b d ú u n d e b   p a r   g ü e d e b   s a a q u i   .  
D e n i   g u b i z   v i n   a x   r a i p y   x n a n   J e s ú s   l a a n y   :   —   A q u ɨ t r u   r á p t i d e b   v i n   .  
C h i y   c u a b y   J e s ú s   :   —   ¿ X í n i i   r n i i b i u   z i y   n a r e   d x a   ,   x n a n a   ?   N e   n a a   g a t l l ɨ   i d z ɨ n y   h o r   x t e n a   .  
P e r   M a r í a   x n a n   J e s ú s   r a i p i a c b ɨ   d e   b n i e t y   n i   c a y u n   s i r v ɨ   r u y   :   —   G u l g a a n y   i r a t e   z e c t i s y   n i   i n i i n y   l a a t   .  
N e   r u y   z u g u a a   x o o p   d e   g u e s   g u i a   n i   r d a a   n i s   p a r   r a c n i a   d e   b n i e t y   I s r a e l   z e c   n i   n á   x c o s t u m b r ɨ d e b   a x   z e c t i   t u b y   g a y u a a g a   l i t r ɨ   n i s   r d a a   l á a n i   t u b y   d e   g u e s q u i   .  
C h i y r u   r a i p y   J e s ú s   d e   b n i e t y   n i   c a y u n   s i r v ɨ q u i   :   —   G u l c h a   d e   g u e s q u ɨ   n i s   .   D e n i   b c h a d o o d e b   d e   g u e s q u i   ,  
a x   r a i p y   J e s ú s   l a a d e b   :   —   A n r e   g u l d é e   d u u d x n i   ,   c h i y   g u l c h a d e e d n i   b n i e t y   n i   c a n i á   c a y a c   g a x t q u ɨ   .   Z i y   x q u e l   b a a n d e b   .  
A x   b n i e t y   n i   c a n i á   c a y a c   g a x t q u i   b a a n b ɨ   p r u e b   n i s   n i   g u c t e g a c   v i n   h o r q u i   ,   s i n   q u ɨ t   g á n t i b   c a l í   n e z   z á n i   .   D e   b n i e t t i s y   n i   c a g u i i z n i   n á n   ,   t e   p u r   l a a d e b   g ü e c á a d e b   n i s   .   C h i y r u   b n i e t y   n i   c a n i á   c a y a c   g a x t q u i   g u r ɨ d x b ɨ   b í i n y
a x   r a i p b ɨ   l a a b   :   —   I r a t e   b n i e t y   n i d o o t e   v i n z a a c   r g u i i z d e b   ,   a x   d e n i   a g ü é e d e b   z i i l n i   ,   c h i y r u   r g u i i z d e b   n i   n á   g u l l i a a r u   .   P e r   a n r e   l i ú   g u l u c h u u   v i n z a a c q u ɨ   p a r   i g a a i z n i   a n r u   .  
N i y   n á   n i d o o t e   m i l a g r ɨ   n i   b a a n y   J e s ú s   .   L a a n y   b a a n n y   m i l a g r ɨ q u i   l á a n i   g u ɨ d x   C a n á   n i   n á   n e z   G a l i l e a   .   Z i y   x q u e l   b l i u u n y   g u e l r n a b e e   n i   n a p n y   a x   g ü e l d i l a a z   d e   x p ɨ n n y   l a a n y   .  
C h i   g u d e e d   g u c   z i y   a x   z é g a c n y   g u ɨ d x   C a p e r n a u m   c u n   x n a n n y   c u n   d e   b e t s n y   c u n   d e   x p ɨ n n y   .   R u y   g u z u g u a a d e b   t u b y   t i o p   d x i   .   (   M t   .   2   1   :   1   2   ‑   1   3   ;   M r   .   1   1   :   1   5   ‑   1   8   ;   L c   .   1   9   :   4   5   ‑   4   6   )  
N e   c u n   a b d z ɨ n g a x   p a s c u   ,   l a n í   x t e   d e   b n i e t y   I s r a e l   ,   a x   g ü e   J e s ú s   J e r u s a l é n   .  
C h i y   l o   l d e d o o   J e r u s a l é n q u i   b d x i a l n y   d e   n i   c a t ó o   d e   g ú u n   c u n   d e   l l í i l y   c u n   d e   p a l o m   n e   d e   b ɨ n y   n i   z u b   l o   m ɨ l l y   c a c h a a   x m ɨ l y   d e   b n i e t y   n i   z á   i r ɨ n q u ɨ   n e z   .  
C h i   g u n á   J e s ú s   z i y   a x   b a n c h u u n y   t u b y   c h i c o t y   c u n   d u u   p a r   g u l é e n y   i r a t e   d e   g ú u n   n e   d e   l l í i l y q u i   l o   l d e d o o q u i   n e   b t ɨ ɨ c h n y   x m ɨ l y   d e   b ɨ n y   n i   c a c h a a   m ɨ l y   n e   b z á a l d z a c n y   x m ɨ l l d e b   .  
C h i y   r a i p n y   d e   n i   c a t ó o   p a l o m   :   —   ¡   G u l d é e   d e n g   r u c   !   ¡   Q u ɨ t   r u n n é t   l i z   X t a d a   z e c   l o   g u e e   !  
C h i y r u   g ü e n e l a a z   d e   x p ɨ n n y   l o   x q u i i t s   D i o s   r u t   r n i i   :   “   A x t   g a t i a   q u ɨ t   i s a a n t i a   n i   r g u a l u a a   l i z b i u   .   ”
C h i y   r a i p y   d e   b ɨ n y   I s r a e l   J e s ú s   :   —   ¿ X i   m i l a g r ɨ   i l i u u b i u   d u n n ɨ   p a r   g a c b e e n   d e c   n a p b i u   g u e l r n a b e e   g ú n b i u   z e e c   ?  
A x   c u a b y   J e s ú s   :   —   G u l t s ɨ l y   y u d o o r é   n e   l o   c h o n   d x i z y   a b z u u b a n i   s t u b y   .  
C h i y   r a i p y   d e   b ɨ n y   I s r a e l q u i   l a a n y   :   —   C u a r e n t a   y   s e i s   i z   g u c l d a a d e b   p a r   b z u u b d e b   y u d o o r é   .   N e   l a a b i u   c u n   c h o n   d x i z y l e z y   a b z u u b b i u n i   s t u b y   .  
P e r   J e s ú s   l a g a c q u ɨ   p u r   x c u e r p ɨ n i y   r n i i n y   c h i   r z e e t n y   y u d o o q u i   .  
P u r   n i n g u i   ,   d e n i   g u b á n y   J e s ú s   x t e   n i   g u t y n y   d e   x p ɨ n n y   g ü e n e l a a z d e b   n i   g u n i i n y   ,   a x   g ü e l d i l a a z d e b   x t i i d x n y   n e   g ü e l d i l a a z z a d e b   n i   c á   l o   x q u i i t s   D i o s   .  
L a l z i   n i   g u z u g u a a   J e s ú s   J e r u s a l é n   ,   c h i   l a n í   p a s c u   ,   z i e n y   d e   b n i e t y   g ü e l d i l a a z   l a a n y   c h i   g u n á d e b   d e   m i l a g r ɨ   n i   b a a n n y   .  
P e r   l a a n y   q u ɨ t   g ü e l d i l a a z t i n y   n i   r n i i d e b   t e   p u r   n á n n a c n y   x a   n á   x g a b d e b   .  
Q u ɨ t   r q u i i n t i   t u   g a i p y   l a a n y   x a   n á   b n i e t y   t e   p u r   l a a n y   n a n c h u u n y   x a   n á   x g a b   c a d   t u b y   b n i e t y   .  
G u u   t u b y   b n i e t y   f a r i s e u   n i   b d i a l á   N i c o d e m o   .   L a a b   g u c b ɨ   t u b y   g u r t i s y   l o   d e   b n i e t y   I s r a e l
a x   g ü e t i x l o b   J e s ú s   t u b y   g u x i n   .   C h i y   r a i p b ɨ   l a a n y   :   —   M a i s t r ɨ   ,   d u n n ɨ   n á n n ɨ   d e c   D i o s   b x i a a l d   l a a b i u   p a r   i l i u u b i u   d u n n ɨ   ,   t e   p u r   r u t e e t e   q u ɨ t   t u   c h a l e e t i   g ú n   s a a   d e   m i l a g r ɨ   n i   r u n b i u   b e l a t i   q u ɨ t   r b e z n é b   D i o s   .  
C h i y   r a i p y   J e s ú s   l a a b   :   —   N a r e   r g u i x t e l d í a   l o o   d e c   e l q u ɨ   n i   q u ɨ t   i b í i   g a l   s t u b y   ,   q u ɨ t   x o   i n i á t i b   g u e l r n a b e e   x t e   D i o s   .  
A x   r a i p y   N i c o d e m o   l a a n y   :   —   P e r   ,   ¿ x ó l e s a   i b í i   g a l   b n i e t r o o   s t u b y   ?   ¿ T a t i x   z e l e e   y a i c q u i b ɨ   p a r   i t s ɨ n y   x n a n b ɨ   l a a b   g u ɨ c h l i u   s t u b y   ?  
J e s ú s   c u a i b n y   :   —   N a r e   r g u i x t e l d í a   l o o   d e c   e l q u ɨ   n i   q u ɨ t   r r u b n i s   n e   n i   q u ɨ t   r b e z n é   S p í r i t u   S a n t   q u ɨ t   x o   y i i u t i b   l o   g u e l r n a b e e   x t e   D i o s   .  
D e   b n i e t y   n i   n a b á n y   z e c   n i   n á   x g a b n i   ,   l o   g u ɨ c h l i u t i s y   n a p d e b   g u e l n a b á n y   .   P e r   d e   b n i e t y   n i   r b e z n é   S p í r i t u   S a n t   p u r   S p í r i t u   S a n t   n a p d e b   s t u b y   g u e l n a b á n y   .  
Q u ɨ t   r z a c a n u   p u r   n i   r n i i a   l i ú   :   “   I r a t e   b n i e t y   g u ɨ c h l i u   n á   p a r   c u e z n é   S p í r i t u   S a n t   .   ”
T e   z e c q u ɨ   n i   r b í i   b i   i r a n e z t e   n e   m a s q u ɨ   r i n d i a g u   c h i   r b í i   b i   ,   p e r   n i c   r s o n u   c a l í   n e z   z é e d n i   o   c a l í   n e z   c h i a n i   .   Z i y g a c z a q u ɨ y   n á   S p í r i t u   S a n t   p a r   c u n   i r a t e   d e   b n i e t y   n i   r b e z n é n y   .  
C h i y r u   r a i p y   N i c o d e m o q u i   l a a n y   :   —   P e r   ,   ¿ t a t i x   z i y   r a c   ?  
J e s ú s   c u a i b n y   :   —   ¡   M a i s t r ɨ l e s a   n o o   l o   d e   b n i e t y   I s r a e l   ,   n e   q u ɨ t   g a n n u   d e   c o s q u ɨ   !  
N a r e   r g u i x t i i a   l o o   d e c   d u n n ɨ   r d x u e e n   n i   n á n n ɨ   n e   n i   a g u n á n   .   P e r   l a a t   q u ɨ t   r e l d i l a a z t i t   n i   r n i i n   .  
B e l a t i   q u ɨ t   r e l d i l a a z t ɨ   c h i   r u e n í a   l a a t   d i i d x   p u r   d e   c o s   x t e   l o   g u ɨ c h l i u r é   ,   ¿ x ó l e s a   c h a l d i l a a z t ɨ   c h i   r u e n í a   l a a t   p u r   d e   c o s   x t e   l l a y a b a a   ?  
’ R u t e e t e   g a d y   t u   c h i a t i   l l a y a b a a   s i n o   q u e   t u b y z i   n i   b i a t   d e s d e   l l a y a b a a   n e   l a a n i y   B n i e t y   n i   b x i a a l d   D i o s   .  
N e   z e c   n i   b c u a a   M o i s é s   t u b y   b é e l d   g u i i b   q u i a   y a g   n e z   l o   y i u b i z   ,   z i y t i z i a c z a   B n i e t y   n i   b x i a a l d   D i o s   s c u a a d e b n y   l o   c r u z y   ,  
t e   p a r   i r a t e   d e   n i   c h a l d i l a a z   l a a n y   q u ɨ t   i n i t t i d e b   l o   D i o s   s i n o   q u e   z a p d e b   g u e l n a b á n y   p a r   c h a z y   c u n   l a a n y   .  
’ N e   d e   t a n t   n i   r c a a z   D i o s   b n i e t y   g u ɨ c h l i u   a x   m a s q u ɨ   t u b y z i   L l i i n n y   ,   p e r   b x i a a l d n y   L l i i n n y   t e   p a r   i r a t e   n i   c h a l d i l a a z   l a a n y   q u ɨ t   i n i t t i d e b   l o   D i o s   s i n o   q u e   g a p d e b   g u e l n a b á n y   p a r   c h a z y   n e z   l o n y   .  
T e   p u r   D i o s   q u ɨ t   b x i a a l d t i n y   L l i i n n y   l o   g u ɨ c h l i u   p a r   i s i á l d n y   c a s t i g u   d e   b n i e t y   s i n o   q u e   p u r   l a a n y   g a p   d e   b n i e t y   p e r d ó n   l o   D i o s   .  
’ E l q u ɨ   n i   r e l d i l a a z   L l i i n   D i o s   ,   q u ɨ t   r i á l d t i b   c a s t i g u   x t e   D i o s   .   P e r   e l q u ɨ   n i   q u ɨ t   r e l d i l a a z   ,   l a a b   a r i á l d b ɨ   c a s t i g u   p u r   n i   q u ɨ t   r e l d i l a a z b ɨ   L l i i n   D i o s   n e   t u b y z i n y   n á n y   L l i i n   D i o s   .  
D e   n i   q u ɨ t   r e l d i l a a z   a r i á l d d e b   c a s t i g u   t e   p u r   c h i   b e e d n y   ,   l a a n y   n i   n á n y   b i e e n y   x t e   D i o s   ,   l a a d e b   m a z r u   b d x u l a a z d e b   n e z   m a l   p u r   n i   r u n d e b   p ú r z i   n i   n á   m a l   .  
I r a t e   d e   n i   r u n   n i   n á   m a l   ,   x í t e e t e   r d x a l a a z t i d e b   b i e e n q u i   a x   q u ɨ t   r b i n u u t i d e b n y   p a r   q u ɨ t   y í a n y   x i   m a l   c a y u n d e b   .  
P e r   d e   b n i e t y   n i   n a b á n y   z e c   n i   r i á l d   n e z   l o   D i o s   ,   l a a d e b   z e n u u d e b   b i e e n y   x t e n n y   p a r   y í a n y   d e c   i r a t e   n i   c a y u n d e b   n á   p u r   D i o s   .  
C h i   g u d e e d   g u c   z i y   ,   J e s ú s   c u n   d e   x p ɨ n n y   g ü e d e b   n e z   J u d e a   .   R u y   g u z u g u a n é n y   l a a d e b   t u b y   t i o p   d x i   a x   b t i u b n i s   d e   x p ɨ n n y   d e   b n i e t y   .  
C h i y   z i y z a   g u ɨ d x   n i   l á   E n ó n   n i   n á   g a x   n e z   S a l i m   ,   J u a n y   B a u t i s t   c a t i u b n i s z a c b ɨ   d e   b n i e t y   p u r   n i   n u u   z i i l y   n i s   n e z q u i   a x   r e   d e   b n i e t y   p a r   r r u b n i s d e b   .  
N i y   g u c q u ɨ y   a n s t e   n i   g u i a g u   J u a n y   B a u t i s t   .  
P e r   t u b y   t i o p   d e   x p ɨ n y   J u a n y   c u n   t u b y   t i o p   d e   n i   z e n u u p a c   l e y   g u z u l o   r c h a a d e b   l o   d i i d x   p u r   x c o s t u m b r ɨ d e b   x a   x q u e l   g a c n i a d e b   .  
C h i y r u   g ü e g a t s d e b   J u a n y   :   —   M a i s t r ɨ   ,   c a u r i e n b i u   d e c   b n i e t y   n i   g u z u g u a n é b i u   d e t s   g u e e u   J o r d á n   n i   b e n é b i u   d u n n ɨ   x t i i d x n i   ,   a n r e   a c a t i u b n i s b ɨ   d e   b n i e t y   n e   i r a t e d e b   a z e n u u   l a a b   .  
C h i y   r a i p y   J u a n y   l a a d e b   :   —   R u t e e t e   q u ɨ t   t u   c h a l e e t i   g a p   g u e l r n a b e e   b e l a t i   D i o s   q u ɨ t   i d e e d n i   .  
L a a t   n a n l d í t   d e c   b i n d i a g t ɨ   g u n i i a   g a t i   n a r e t i a   n a a   C r i s t   s i n o   q u e   n a r e   z e l d t i z i a   p a r   z e d t i x t e e g a   p u r   l a a n y   .  
D u n n ɨ   n á n n ɨ   d e c   r u t   r a c   t u b y   s a a   ,   b í i n y   n á   n i   z u g u a n é   d x a a p   .   N e   x m i g u   b í i n y   n i   z u g u a n é   l a a b   h o r q u i   ,   q u e s e n t i a n d   r z a c l a a z b ɨ   c h i   r i n d i a g b ɨ   s u l o   i n i i   b í i n y   d i i d x   .   A n r e   z i y z a q u ɨ y   q u e s e n t i a n d   r z a c l a a z a   p u r   l a a n y   ,  
n e   l a a n y   z e l a a r u p a c   g a c n y   n i   m a z r u   s a c   .   N a r e   a x   z e l a a r u p a c   g a c a   g u l l i a a r u   q u e   l a a n y   p u r   n i   m a z r u   s a c n y   .  
T e   p u r   n i   z é e d   d e s d e   l l a y a b a a   ,   l a a n y   n á   n i   r n a b e e n y   l o   i r a t e   .   P e r   b ɨ n g u ɨ c h l i u   ,   b ɨ n g u ɨ c h l i u t i s y   l a a b   n e   p ú r z i   n i   n u u   l o   g u ɨ c h l i u   r z e e t b ɨ   .   P e r   n i   z é e d   d e s d ɨ   l l a y a b a a   l a a n y   n á   n i   r n a b e e n y   i r a t e
a x   r u e e n y   n i   a g u n á n y   n e   n i   a b i n d i a g n y   .   P e r   r u t e e t e   q u ɨ t   r e l d i l a a z t i   n i   r n i i n y   .  
B e l a t i   n u u   n i   r e l d i l a a z   x t i i d x n y   ,   n i y   z e l o   d e c   p ú r z i   d i d x l d í   n á   x t i i d x   D i o s   .  
N e   e l q u ɨ   n i   z é e d   p u r   D i o s   ,   l a a n y   r u e e n y   x t i i d x   D i o s   p u r   n i   b i a l o   b d e e d   D i o s   l a a n y   g u e l r n a b e e   p u r   S p í r i t u   S a n t   .  
D i o s   r c a a z n y   L l i i n n y   a x   b s á a n n y   i r a t e   l a z n a a n y   .  
N e   t u t i x   n i   r e l d i l a a z   L l i i n n y   ,   l a a b   n a p b ɨ   g u e l n a b á n y   p a r   c h a z y   n e z   l o   D i o s   .   P e r   e l q u ɨ   n i   q u ɨ t   r e l d i l a a z   L l i i n n y   ,   q u ɨ t   x o   g a p t i b   g u e l n a b á n y q u i   s i n o   q u e   l a a b   r i á l d b ɨ   c a s t i g u   x t e   D i o s   .  
D e   f a r i s e u   g u c b e e d e b   d e c   m a z r u   z i e n y   x p ɨ n y   J e s ú s   n e   m a z r u z a   c a t i u b n i s n y   d e   b n i e t y   q u e   J u a n y   ,  
(   m a s q u ɨ   n i   n á p a c n i   g a t i   J e s ú s t i   r t i u b n i s   b n i e t y   s i n o   q u e   d e   x p ɨ n n y   )   .  
N e   p u r   n i   g u c b e e d e b   z i y   n i n g u i   a x   b d i i a   J e s ú s   n e z   J u d e a   p a r   z é n y   n e z   G a l i l e a   s t u b y   .  
P e r   c h i   z é n y   n e z   G a l i l e a   n a p n y   q u e   g u d e e d n y   n e z   S a m a r i a   .  
A x   b d z ɨ n n y   t u b y   g u ɨ d x   x t e   S a m a r i a   r u t   l á   S i c a r   ,   g a x   l o   l i u   n i   b g u a a d   t o   J a c o b   l l i n g a a n b ɨ   t o   G u s é   .  
R u y   n á   b z i a   n i   r n i i d e b   ,   b z i a   x t e   J a c o b   .   N e   c u n   J e s ú s   a b d x a n y   c a z a n y   a x   g u r i n y   r u u   b z i a q u i   z é e d t i   g a c   l a i d x i   .  
C h i y   d e   x p ɨ n n y   g ü e d e b   l á a n i   g u ɨ d x q u i   p a r   g ü e s i i d e b   n i   i q u i i n d e b   .  
H o r q u i   a x   b d z ɨ n y   t u b y   g u n a a   S a m a r i a   r u u   b z i a q u i   z e l d e e b   n i s   ,   a x   r a i p y   J e s ú s   l a a b   :   —   B g u a a d   n a r e   d u u d x   n i s   .  
P e r   c u n   d e   b n i e t y   I s r a e l   q u ɨ t   r c h a a t i d e b   d e   b n i e t y   S a m a r i a   ,   a x   c u a b y   g u n a a q u i   l o n y   :   —   B ɨ n y   S a m a r i a   n a r e   n e   ,   ¿ x í l e s a n i   r n a a b b i u   n i s   l u a a   n e   b n i e t y   I s r a e l   l a a b i u   ?  
C h i y   r a i p y   J e s ú s   l a a b   :   —   B e l r u l a t i   r a c b i i u   n i   r c a a z   D i o s   i n ɨ ɨ d x n y   l i ú   ,   n e   b e l r u l a t i   r a c b i i u   t ú   c a n a a b   n i s   l i ú   ,   l i ú   s n a a b u   n i s   n a r e   n e   n a r e   s n ɨ ɨ d x a   l i ú   n i s   n i   r g u a a d   g u e l n a b á n y   .  
C h i y r u   r a i p y   g u n a a q u i   J e s ú s   :   —   D a d   ,   n i c l ɨ   q u ɨ t   x i   c a a b i u   p a r   c u é e b i u   n i s   ,   n e   b z i a c   q u e s e n t i a n d   g u é t n i   .   ¿ C a l í l e s a   c h a c á a b i u   n i s   n i   r g u a a d   g u e l n a b á n y   ?  
B z i a c   d e s d ɨ   t o   x p ɨ n g u l n ɨ   J a c o b   b s a n n é n y   d u n n ɨ   ,   n e   l a g a c   n i s q u ɨ   b q u i i n b ɨ   z i y z a   d e   l l i i n b ɨ   c u n   d e   l a d x a a   x t e n d e b   .   A n r e   ,   ¿ t a t i x   m a z r u   s a c b i u   q u e   l a a b   ?  
C h i y   r a i p y   J e s ú s   l a a b   :   —   I r a t e   d e   n i   r é e   n i s q u ɨ   r d x á g a c d e b n i   s t u b y   .  
P e r   e l q u ɨ   n i   g u é e   n i s   n i   i d e e d a   ,   q u ɨ t r u   c h ú u t i   d x i   i d x á b n i   .   T e   p u r   n i s   n i   i d e e d a b   z a c n i   n e z   l á a n b ɨ   z e c   t u b y   r u t   q u ɨ t   r b e z t i   r a c h y   n i s   ,   a x   a n a p b ɨ   g u e l n a b á n y   p a r   c h a z y   .  
C h i y r u   r a i p y   g u n a a q u i   l a a n y   :   —   D a d   ,   b g u a a d b i u   n a r e   n i s q u i   p a r   q u ɨ t r u   i b í i t i   i d x a a   n i s   ,   n i c l ɨ z a   q u ɨ t r u   g u e d l d é e t i a n i   r u c   .  
J e s ú s   r a i p y   l a a b   :   —   Q u e g ü e t ɨ d x   c h i a l u   ,   c h i y r u   g u e e d u   .  
G u n a a q u i   a x   c u a i b b ɨ   :   —   Q u ɨ t t i   c h i a l a   .   C h i y r u   r a i p y   J e s ú s   l a a b   :   —   G u l d í c u   q u ɨ t t i   c h i a l u
t e   p u r   a g u c   g a a y   c h i a l u   r u u   ,   n e   a n r e   b n i e t y   n i   r b e z n í u   n i c l ɨ   g a t i   c h i a l u   r a c b ɨ   .   P u r   n i n g u i   ,   d i d x l d í c   n á   n i   r n i i u   .  
C h i   b i n d i a g   g u n a a q u i   z i y   ,   a x   r a i p b ɨ   l a a n y   :   —   D a d   ,   r d x a l u a a   d e c   l a a b i u   n á b i u   t u b y   p r o f e t   x t e   D i o s   .  
D e   t o   x p ɨ n g u l   g u l a l n ɨ   q u i a   d a n y q u ɨ   b t o d e b   D i o s   ,   p e r   l a a t   n i   n á t   b n i e t y   I s r a e l   r n i i t   d e c   J e r u s a l é n   n á   p a r   i t o n   D i o s   .  
J e s ú s   a x   c u a i b n y   :   —   G u n a a   ,   g ü e l d i l a a z   n a r e   d e c   t e r u   i d z ɨ n y   d x i   n i   i t o t   X t a d n ɨ   D i o s   s i n   q u ɨ t   g u e e d t i t   n i c l ɨ   q u i a   d a n y q u ɨ   n i c l ɨ z a   J e r u s a l é n   .  
L a a t   n i c l ɨ   q u ɨ t   g á n t ɨ   t ú   r t o t   .   P e r   d u n n ɨ   n a n c h u u n   t ú   r t o n   t e   p u r   l o   d e   b n i e t y   I s r a e l   z á   n i   g ú n   p e r d ó n   b n i e t y   .  
N e   a n a c r e   a b d z ɨ n y   d x i   n i   i r a t e   d e   n i   g u l d í p a c   r t o   D i o s   ,   s t o d e b n y   z e c   n i   r i á l d   p u r   S p í r i t u   S a n t   x t e n n y   .   T e   p u r   z i y   r c a a z   X t a d n ɨ   D i o s   g ú n   d e   n i   r t o   l a a n y   .  
D i o s   n á   S p í r i t   n e   d e   n i   r t o   l a a n y   n á   p a r   i t o d e b n y   d i b y q u i a   d i b y l a a z d e b   p u r   S p í r i t u   S a n t   .  
C h i y r u   r a i p y   g u n a a q u i   J e s ú s   :   —   N a r e   n á n n a   d e c   n á   p a r   g u e e d   M e s í a s   n i   l á z a   C r i s t   .   N e   c h i   g u e e d n y   l a a n y   q u i x t e e n y   l o n   i r a t e   .  
J e s ú s   r a i p y   l a a b   :   —   N a r e n i y   C r i s t   n i   r z e e t u   ,   l a a n i y   c a n i n é n y   l i ú   .  
H o r q u i   a x   b d z ɨ n y   d e   x p ɨ n n y   n e   b d x a l o d e b   p u r   n i   c a y u e n é n y   t u b y   g u n a a   d i i d x   .   P e r   n i c   t u b y d e b   q u ɨ t   n i n a b d i i d x t i   l a a n y   x i   r c a a z   g u n a a q u i   ,   o   x i y   c a y u e e d e b   .  
C h i y   g u n a a q u i   b s á a n a c b ɨ   r i i   x t e n b ɨ   r u u   b z i a q u i   ,   a x   z é g a c b ɨ   l á a n i   g u ɨ d x   r u t   g ü e g a t s b ɨ   d e   b n i e t y   :  
—   G u l t a g u i a a   t u b y   b n i e t y   n i   a g u n i i   n a a   i r a t e   n i   a b a a n i a   .   ¿ L a d x a   g a t i   l a a b ɨ y   C r i s t   ?  
C h i y r u   b d i i a d e b   l á a n i   g u ɨ d x q u i   p a r   g ü e d e b   r u t   z u g u a a   J e s ú s   .  
P e r   l a l z i   n i   z é   g u n a a q u i   l á a n i   g u ɨ d x q u i   ,   d e   x p ɨ n y   J e s ú s   r a i p d e b   l a a n y   :   —   M a i s t r ɨ   ,   b q u i i n b i u   .  
P e r   l a a n y   r a i p n y   l a a d e b   :   —   N a r e   a   n i   i q u i i n i a   r á p a   ,   p e r   q u ɨ t   g á n t i t   x a   n á n i   .  
A x   g u z u l o   r n a b d i d x s a a   d e   x p ɨ n n y   :   —   ¿ L a d x a   n u u   n i   b d e e d   x i   b q u i i n n y   ?  
C h i y r u   r a i p y   J e s ú s   l a a d e b   :   —   G u e l r q u i i n y   x t e n a   n á   g ú n a   z e c   n i   r c a a z   D i o s   n i   b x i a a l d   n a r e   ,   n e   y a l o z a   g ú n a   n i   g u n i i n y   g ú n a   .  
L a a t   r n i i t   :   “   R i e e d x   s t a p   b ú i u   p a r   s u l o   g a c   d e   c o s e c h   .   ”   P e r   n a r e   r n i i a   l a a t   :   G u l d i a s l o   ,   g u l g u i a a   l o   d e   y á a n   a g u l d   i d o p n i   .  
N e   b n i e t y   n i   r t o p n i   ,   r c á a b   n i   r i á l d b ɨ   p u r   d z ɨ ɨ n y   n i   r u n b ɨ   .   C h i y   d e   c o s e c h   n i   r t o p b ɨ   a   n á   p a r   r u t   n u u   g u e l n a b á n y   p a r   c h a z y   .   Z i y   x q u e l   a x   z e c l ɨ   n i   r z i b i n n i   n e   z e c l ɨ z a   n i   r t o p n i   t u b y l o t e   r z a c l a a z d e b   .  
D i d x l d í q u ɨ y   n i   r n i i   b n i e t y   :   “   I r ɨ n y   n i   r u n   d z ɨ ɨ n y   c h i y   i r ɨ n y   n i   r t o p   d e   g u e l n a z a a c   .   ”
N a r e   b x i a a l d a   l a a t   p a r   c h a t o p t ɨ   d e   g u e l n a z a a c   r u t   n i c l ɨ   q u ɨ t   b a a n t i t   d z ɨ ɨ n y   .   I r ɨ n q u ɨ   d e   n i   b a a n y   d z ɨ ɨ n y   ,   c h i y   l a a t   g ü e t o p   ,   g ü e t o p z i t   d e   g u e l n a z a a c   r u t   b a a n d e b   d z ɨ ɨ n y   .  
Z i e n y   d e   b n i e t y   S a m a r i a q u i   g ü e l d i l a a z   J e s ú s   p u r   x t i i d x   g u n a a q u i   ,   c h i   r a i p b ɨ   l a a d e b   :   “   A g u n i i n y   n a r e   i r a t e   n i   a b a a n i a   .   ”
P u r   n i n g u i   ,   c h i   b d z ɨ n y   d e   b n i e t y   S a m a r i a q u i   r u t   z u g u a a   J e s ú s   a x   b a n l a s d e b   l o n y   p a r   s u g u a n é n y   l a a d e b   .   C h i y   g u z u g u a n é n y   l a a d e b   t i o p   d x i   .  
N e   m a z r u   z i e n d e b   g ü e l d i l a a z   l a a n y   c h i   b i n d i a g d e b   n i   r n i i n y   .  
C h i y r u   r a i p d e b   g u n a a q u i   :   —   A n r e   a g a t i   p u r z í t i   n i   g u n i i u   d u n n ɨ   r o l d i l a a z n ɨ n y   s i n o   q u e   p u r   n i   l a g a c   d u n n ɨ   a b i n d i a g n ɨ   n i   r n i i n y   .   N e   n a n l d í n   d e c   l a a n i y   C r i s t   n i   r u n   p e r d ó n   b n i e t y   g u ɨ c h l i u   .  
C h i   g u d e e d   t i o p   d x i q u i   ,   J e s ú s   b d i i a n y   n e z   S a m a r i a   a x   g ü e l a a r u   z é n y   n e z   G a l i l e a   .  
M a s q u ɨ   l a g a c   l a a n y   g u n i i n y   d e c   n i c   t u b y   p r o f e t   n i   r n i i   x t i i d x   D i o s   q u ɨ t   r á p t i d e b   d i d x d o o   l a a b   l a d x b ɨ   ,  
p e r   c h i   b d z ɨ n n y   n e z   G a l i l e a   ,   d e   b n i e t y   n e z q u i   g ü e n q u ɨ   b a a n d e b   r e c i b i r n y   .   T e   p u r   g ü é z a d e b   l a n í   p a s c u   J e r u s a l é n   a x   g u n á d e b   i r a t e   n i   b a a n n y   l o   l a n í q u i   .  
C h i y r u   g u b í i   b i e c q u i   J e s ú s   C a n á   t u b y   g u ɨ d x   x t e   G a l i l e a   ,   r u t   b a a n n y   g u c t e g a c   n i s   v i n   .   N e   g u ɨ d x   C a p e r n a u m   g u u   t u b y   x p ɨ n y   r e y   n i   r a c x ú   t u b y   l l i i n n i   .  
C h i   g u c b e e   x p ɨ n y   r e y q u i   d e c   a b d z ɨ n y   J e s ú s   n e z   G a l i l e a   x t e   n i   b z a n y   n e z   J u d e a   ,   a x   g ü e b   r u t   b d z ɨ n n y   n e   b a n l a s b ɨ   l o n y   p a r   c h a s i a c n y   l l i n g a a n b ɨ   n i   a p a c m e r   g a t y   .  
A x   r a i p y   J e s ú s   l a a b   :   —   L a a t   a x t   b e l   q u ɨ t   i n i á t   x i   d e   s e n y   o   d e   m i l a g r ɨ z a   ,   q u ɨ t   c h a l d i l a a z t ɨ   .  
P e r   x p ɨ n y   r e y q u i   c u a i b b ɨ   :   —   D a d   ,   g u e e l d z i   q u e d a a b i u   a n s t e   g a t y   l l i n g a a n a   .  
C h i y r u   r a i p y   J e s ú s   l a a b   :   —   Q u e b i e c q u i   l i z u   .   A   l l i n g a a n u   a n u z a a c   .   B n i e t q u i   g ü e l d i l a a z b ɨ   x t i i d x   J e s ú s   a x   z í a g a c b ɨ   l i z b ɨ   .  
C h i y   l a l z i   n i   z í a b   a x   g ü e c h a l o   d e   x m o s b ɨ   l a a b   ,   r a i p d e b   l a a b   :   —   A   l l i n g a a n b i u   a n u z a a c   .  
C h i y   g u n a b d i i d x b ɨ   l a a d e b   x o r t i   g u z u l o   r u z a a c   l l i i n b ɨ   ,   a x   r a i p d e b   l a a b   :   —   N a y   z e c t i   r c a   t u b y   g u d x i   g u b i c á   x l i a a q u i   .  
C h i y r u   b i a b   b n i e t q u i   c u e n d   d e c   h ó r a c q u i y   r a i p y   J e s ú s   l a a b   :   “   A   l l i n g a a n u   a n u z a a c   .   ”   A x   l a a b   n e   i r a t e   d e   x f a m i l b ɨ   g ü e l d i l a a z d e b   J e s ú s   .  
N i y   g u c   n i   r r o p   m i l a g r ɨ   n i   b a a n y   J e s ú s   n e z   G a l i l e a   c h i   b z a n y   n e z   J u d e a   .   D e s d e   a n s t e   n i   g u r i x t i   g u ɨ c h l i u   a g a c   n u u   t u b y   n i   l á   D i i d x   .   L a a n y   r b e z n é n y   D i o s   n e   l a a z a c n y   n á n y   D i o s   .  
N i   l á   D i i d x q u i   a g a c   r b e z n é n y   D i o s   c h i   g u z u l o   g u r i x t i   g u ɨ c h l i u   .  
I r a t e   d e   n i   n u u   ,   p u r   l a a n y   g u c c h u u d e n i   .   X í t e e t e   q u ɨ t   x i   n u u t i   n i   q u ɨ t   g u c   p u r   l a a n y   .  
N e   l a a n y   n a p n y   g u e l n a b á n y   .   C h i y   g u e l n a b á n y q u i   n á   b i e e n y   p a r   i r a t e   b ɨ n g u ɨ c h l i u   .  
N e   b i e e n q u i   r z i e e n n y   x q u e l r i e n y   d e   b n i e t y   a x   m á s   ,   m á s   n a c a y   x q u e l r i e n d e b   ,   p e r   q u ɨ t   x o   s u t i   g u e l n a c a y q u i   l o   b i e e n y   x t e   D i o s   .  
G u u   t u b y   b n i e t y   n i   b d i a l á   J u a n y   .   L a a b   n á   n i   b c u a b e e   D i o s
p a r   g u c b ɨ   z e c   t u b y   t e s t i g u   .   B e d g ü e e b   d i i d x   p u r   x p i e e n y   D i o s   t e   p a r   c h a l e e   c h a l d i l a a z   i r a   b n i e t n y   .  
P e r   g a t i   l a g a c t i   J u a n y   g u c   x p i e e n y   D i o s   s i n o   q u e   l a a b   b e e d t i s b ɨ   p a r   g u d i x t e e b   l o   d e   b n i e t y   x a   n á   b i e e n q u i   .  
T e   p u r   n i   n á   m e r p a c   b i e e n q u i   l a a n y   r z i e e n n y   x q u e l r i e n y   i r a   b n i e t y   g u ɨ c h l i u   n e   a b e e d n y   l o   g u ɨ c h l i u   .  
L a a n y   g u z u g u a a n y   l o   g u ɨ c h l i u   ,   n e   m a s q u ɨ   p u r   l a a n y   n u u   g u ɨ c h l i u   ,   p e r   d e   b n i e t y   g u ɨ c h l i u   q u ɨ t   n i z i g u e l d t i   n i u m b e e   l a a n y   z e c   n i   n á   p a r   n i u m b e e d e b n y   .  
B d z ɨ n n y   l o   g u ɨ c h l i u   l o   n a c i o n y   I s r a e l   n e   m a s q u ɨ   g u c n y   b n i e t y   I s r a e l   ,   p e r   d e   b n i e t y   I s r a e l   q u ɨ t   b a a n t i d e b   c u e n d   x t i i d x n y   .  
P e r   m a s q u ɨ   z i y   ,   i r a t e   d e   n i   b a a n y   c u e n d   l a a n y   n e   g ü e l d i l a a z d e b n y   ,   b d e e d n y   l a a d e b   g u e l r n a b e e   p a r   g a c d e b   d e   l l i i n   D i o s   .  
N e   m a s q u ɨ   l l i i n   b n i e t y   g u ɨ c h l i u   r a c   b n i e t y   o   m a s q u ɨ z a   p u r   x g a b   b n i e t y   o   p u r   z é e d   g a n   g a p   b n i e t y   l l i i n n i   l o   g u ɨ c h l i u r é   ,   p e r   g a t i   p u r   z i y t i   a   n á   b n i e t y   l l i i n   D i o s   s i n o   q u e   p u r   g u e l r e l d i l a a z   a n á d e b   l l i i n   D i o s   .  
D i i d x   n i   g u l e z n é   D i o s   d e s d ɨ   g u l o   ,   l a a n y   g u c n y   b n i e t y   .   G u b á n n y   l o   g u ɨ c h l i u   c u n   d u n n ɨ   ,   n e   g a t i   g u l l i e e z t i   n á   g u e l r c a a z   x t e n n y   a x   p ú r p a c   d i d x l d í   g u n i i n y   .   (   D u n n ɨ   g u n á n   g u e l r n a b e e   x t e n n y   ,   g u e l r n a b e e   n i   c u á a n y   p u r   l a a t i s n y   n á n y   L l i i n p a c   D i o s   .   )  
C h i   b e n é   J u a n y   d e   b n i e t y   x t i i d x n y   ,   l a a b   g u n i i b   :   —   J e s ú s r e n i y   n á   n i   r z e e t a   c h i   g u n i i a   l a a t   d e c   n i   g u e e d   d e s p u é s   d e   n a r e   l a a n y   m a z r u   s a c n y   q u e   n a a   t e   p u r   a g a c   g u l a l   n u u n y   q u e   n a r e   .  
P u r   l a a n y   i r a t e c n ɨ   a r d x a p n ɨ   g u e l n a b á n y   z e c t i s p a c   l a a n y   ,   n e   d x i   p u r   d x i   c a y u n l d e e n y   q u i a n   .  
P u r   M o i s é s   b n ɨ ɨ d x   D i o s   d u n n ɨ   l e y   x t e n n y   ,   p e r   p u r   J e s u c r i s t   g u c b e e l d í n   x a   n á   g u e l r c a a z   n e   d i d x l d í   x t e n n y   .  
G a d y   c h ú u t i   d x i   i n i á   b n i e t y   D i o s   ,   q u e s o l t i s y   t u b y z i   L l i i n n y   n i   r b e z n é   l a a n y   a b l i u u   d u n n ɨ   x a   n á   D i o s   .   (   M t   .   3   :   1   1   ‑   1   2   ;   M r   .   1   :   7   ‑   8   ;   L c   .   3   :   1   5   ‑   1   7   )  
C h i y   d e s d e   J e r u s a l é n   d e   g u r t i s y   x t e   d e   b n i e t y   I s r a e l   b x i a a l d d e b   d e   b x o z   c u n   d e   b ɨ n y   l e v i t a s   p a r   g ü e n a b d i i d x d e b   J u a n y   t ú   n á b   .   C h i y r u   b e n é   J u a n y   l a a d e b   d i i d x   .  
B z i r u u b   i r a i r a t e   l o d e b   r a i p b ɨ   l a a d e b   :   —   G a t i   n a r e t i a   n a a   C r i s t   .  
C h i y   g u b í i   g u n a b d i i d x d e b   l a a b   :   —   ¿ T ú z a   l i ú   d x a   ?   ¿ T a   l i ú y   E l í a s   ?   J u a n y   c u a i b b ɨ   :   —   G a t i   n a r e t i a y   .   C h i y r u   r a i p d e b   l a a b   :   —   O   ,   ¿ t a   l i ú y   p r o f e t   n i   n á   p a r   g u e e d   ?   L a a b   c u a i b b ɨ   :   —   G a t i   n a r e t i a y   .  
C h i y   r a i p d e b   l a a b   :   —   ¿ T ú z a   l i ú   ,   p ɨ s   ?   T e   p u r   n á   p a r   c h o n é n   r s o n   l o   d e   n i   b x i a a l d   d u n n ɨ   .   G u n i i   d u n n ɨ   t ú   l i ú   .  
C h i y r u   r a i p y   J u a n y   l a a d e b   :   —   N a r e   n a a   t u b y   n i   r b ɨ x t i a   n e z   l o   y i u b i z   r u t   q u ɨ t   t u   r b e z t i   :   “   G u l g a a n y   t u b y   l d í   n e z   p a r   X t a d n ɨ   n i   r n a b e e ”   ,   z e c   n i   g u n i i   p r o f e t   I s a í a s   d e s d ɨ   g u l a l   .  
C h i y r u   d e   b ɨ n y   n i   b x i a a l d   d e   f a r i s e u   p a r   i n i n é d e b   J u a n y   ,  
g u n a b d i i d x d e b   l a a b   :   —   B e l a t i   g a t i   l i ú   n o o   C r i s t   n i c z a   E l í a s   ,   n i c z a   p r o f e t   n i   n á   p a r   g u e e d   ,   ¿ x i z a n i   r t i u b n i s u   b n i e t y   p ɨ s   ?  
J u a n y   a x   c u a i b b ɨ   l o d e b   :   —   N a r e   r t i u b n i s a   c u n   n i s   .   P e r   l o t   n u u   t u b y   b n i e t y   n i   g a d y   g u m b e e t i t   .  
N e   l a a n i y   n á   p a r   g u e e d   d e s p u é s   d e   n a r e   ,   a x   n i c l ɨ   l o   x c u r a c h n y   q u ɨ t   r i á l d t i   i x a i c q u i a   t e   p u r   m a z r u   s a c n y   q u e   n a r e   .  
I r a t e   d e   c o s r é   g u c   n e z   r u t   l á   B e t á b a r a   ,   n i   n á   s t u b y   l a d   r u u   g u e e u   J o r d á n   r u t   b t i u b n i s   J u a n y   d e   b n i e t y   .  
C h i   b r a g u e e l   s t u b y   d x i   ,   J u a n y   g u n á b   d e c   z e d z ɨ n g a x   J e s ú s   r u t   z u g u a a b   ,   a x   g u n i i b   :   —   G u l g u i a a   .   B n i e t r e n i y   a b c u a b e e   D i o s   p a r   g a t y n y   z e c   t u b y   C o r d e r   p u r   d e   x t u l d   b n i e t y   g u ɨ c h l i u   .  
L a a n i y   r z e e t a   c h i   g u n i i a   l a a t   :   “   D e s p u é s   d e   n a r e   g u e e d   t u b y   b n i e t y   n i   m a z r u   s a c   q u e   n a a   ,   t e   p u r   l a a n y   a g a c   g u l a l   n u u n y   q u e   n a a   .   ”
N e   n i c l ɨ   n a r e   q u ɨ t   g u c b e e t i a   d e c   l a a n i y   n á   p a r   g u e e d n y   ,   p e r   n a r e   z e l d a   p a r   c a t i u b n i s a   d e   b n i e t y   c u n   n i s   p a r   c h a l e e   g u m b e e   d e   b n i e t y   I s r a e l   l a a n y   .  
Z i y z a   r a i p y   J u a n y   l a a d e b   :   —   N a r e   g u n á a   b i a t   S p í r i t u   S a n t   l l a y a b a a   z e c   t u b y   p a l o m   a x t q u ɨ   q u i a n y   .  
M a s q u ɨ   q u ɨ t   r u m b e e t i a n y   ,   p e r   n i   b x i a a l d   n a r e   p a r   i t i u b n i s a   c u n   n i s   l a a n y   g u n i i n y   n a r e   :   “   C h i   i n i o o   y i a t   S p í r i t u   S a n t   a x t   q u i a   t u b y   b n i e t y   ,   l a a n i y   n á   n i   r t i u b n i s n y   b n i e t y   c u n   S p í r i t u   S a n t   .   ”
N a r e   a g u n á a n y   ,   n e   n a n l d í z a c a   d e c   l a a n y   n á n y   L l i i n   D i o s   .  
C h i   b r a g u e e l   s t u b y   d x i   d e n i   z u g u a n é   J u a n y   t i o p   d e   x p ɨ n b ɨ   ,  
c h i   g u n á b   z e t e e d   J e s ú s   ,   a x   g u n i i b   :   —   G u l g u i a a   .   B n i e t r e n i y   a b c u a b e e   D i o s   p a r   g a t y n y   z e c   t u b y   C o r d e r   .  
C h i   b i n d i a g   i r o p t e   d e   x p ɨ n b ɨ   z i y   ,   a x   g u z a n a l d d e b   J e s ú s   .  
D e n i   b z i e c q u i l o   J e s ú s   ,   c h i   g u n á n y   z a n a l d d e b   l a a n y   ,   a x   r a i p n y   l a a d e b   :   —   ¿ X i   r g u í i l y t ɨ   ?   L a a d e b   a x   c u a i b d e b   :   —   M a i s t r ɨ   ,   ¿ c a l í   r b e z b i u   ?  
C h i y r u   r a i p y   J e s ú s   l a a d e b   :   —   G u l t a a   t e   í g u i a a t   .   C h i y r u   g ü e d e b   p a r   g u n á d e b   c a l í   r b e z n y   ,   a x   b i a n n é d e b n y   d x i q u i   ,   t e   p u r   z e c t i   r c a   t a p   g u d x i y   .  
T u b y   d e   x p ɨ n y   J u a n y   n i   g ü e n a l d   J e s ú s   ,   p u r   n i   b i n d i a g b ɨ   n i   g u n i i   J u a n y   ,   l a a b   b d i a l á b   A n d r é s   b e t s   S i m ó n y   B e d   .  
A n d r é s q u i   n i d o n i d o o t e   b e t s b ɨ   S i m ó n y   g ü e t í i l y b ɨ   a x   r a i p b ɨ   l a a b   :   —   A b d x i a l n ɨ   M e s í a s   (   z e l o   d i i d x q u i   ,   C r i s t   )   .  
C h i y r u   g ü e n é   A n d r é s   S i m ó n y   r u t   z u g u a a   J e s ú s   c h i y   c h i   g u n á   J e s ú s   l a a b   a x   g u n i i n y   :   —   L i ú y   S i m ó n y   ,   l l i n g a a n   J o n á s   ,   p e r   a n r e   i d i a l o o   C e f a s   (   z e l o   d i i d x q u i   ,   B e d   )   .  
C h i   b r a g u e e l   s t u b y   d x i   J e s ú s   b a a n n y   x g a b   c h i a n y   n e z   G a l i l e a   a x   b d x á a n y   L i b y   .   C h i y   r a i p n y   l a a b   :   —   Q u e d a n a l d   n a r e   .  
L i b y r é   g u ɨ d x   B e t s a i d a   n á   l a d x b ɨ   r u t   z á   B e d   c u n   A n d r é s   .  
C h i y r u   g ü e t í i l y   L i b y   N a t a n a e l   ,   a x   r a i p b ɨ   l a a b   :   —   A b d x i a l n ɨ   b n i e t y   n i   r z e e t   M o i s é s   l o   l i b r ɨ   x t e   l e y   ,   n e   l a a z a c n i y   n i   r z e e t   d e   p r o f e t   n i   b c u a a   x t i i d x   D i o s   .   L a a n i y   J e s ú s   l l i n g a a n   G u s é   n i   z á   g u ɨ d x   N a z a r e t   .  
C h i y   c u a b y   N a t a n a e l   :   —   ¿ T a t i x   n u u   b n i e t y   N a z a r e t   n i   n á   g ü e n   ?   C h i y r u   r a i p y   L i b y   l a a b   :   —   E d a g u i a a   c a n i o o   .  
C h i   g u n á   J e s ú s   z é e d   N a t a n a e l   ,   a x   g u n i i n y   :   —   R u r é n   z é e d   t u b y   b n i e t y   n i   n á   m e r p a c   b n i e t y   I s r a e l   .   N e   q u ɨ t   x i   e n g a n y t i   r u n b ɨ   b n i e t y   .  
C h i y r u   g u n a b d i i d x   N a t a n a e l   l a a n y   :   —   ¿ X o   r u m b e e b i u   n a r e   ?   J e s ú s   a x   c u a i b n y   :   —   A n s t e   n i   c u i d x   L i b y   l i ú   ,   c h i   z u g o o   l l a a   y a g   h i g   ,   c h i y   g u n á a   l i ú   .  
C h i y   r a i p y   N a t a n a e l   l a a n y   :   —   M a i s t r ɨ   ,   l a a b i u   n á b i u   L l i i n   D i o s   .   L a a b i u   n á b i u   R e y   x t e   I s r a e l   .  
C h i y r u   a x   c u a b y   J e s ú s   l o b   :   —   L i ú   r e l d i l a a z u   n a r e   p u r z i   n i   g u n i i a   l i ú   d e c   g u n á a   l i ú   l l a a   y a g   h i g   .   P e r   t e r u   m a z r u   n i   i n i o o   q u e   n i   a g u n o o   .  
Z i y z a   r a i p y   J e s ú s   l a a b   :   —   N a r e   n a n c h u u a   d e c   l a a t   s n i á t   z u l l a l   l l a y a b a a   n e   s n i á z a c t ɨ   d e   á n g l ɨ   x t e   D i o s   r i e e p d e b   l l a y a b a a   n e   r i a t z a d e b   a x t   q u i a   B n i e t y   n i   b x i a a l d   D i o s   l o   g u ɨ c h l i u   .  
N i   r i o n   d x i   ,   a x   g u u   t u b y   s a a   l á a n i   g u ɨ d x   C a n á   n i   n á   n e z   G a l i l e a   .   C h i y   n é   x n a n   J e s ú s   z u g u a a   r u y   ,  
n e   n é z a   J e s ú s   c u n   d e   x p ɨ n n y   b d ú u n d e b   p a r   g ü e d e b   s a a q u i   .  
D e n i   g u b i z   v i n   a x   r a i p y   x n a n   J e s ú s   l a a n y   :   —   A q u ɨ t r u   r á p t i d e b   v i n   .  
C h i y   c u a b y   J e s ú s   :   —   ¿ X í n i i   r n i i b i u   z i y   n a r e   d x a   ,   x n a n a   ?   N e   n a a   g a t l l ɨ   i d z ɨ n y   h o r   x t e n a   .  
P e r   M a r í a   x n a n   J e s ú s   r a i p i a c b ɨ   d e   b n i e t y   n i   c a y u n   s i r v ɨ   r u y   :   —   G u l g a a n y   i r a t e   z e c t i s y   n i   i n i i n y   l a a t   .  
N e   r u y   z u g u a a   x o o p   d e   g u e s   g u i a   n i   r d a a   n i s   p a r   r a c n i a   d e   b n i e t y   I s r a e l   z e c   n i   n á   x c o s t u m b r ɨ d e b   a x   z e c t i   t u b y   g a y u a a g a   l i t r ɨ   n i s   r d a a   l á a n i   t u b y   d e   g u e s q u i   .  
C h i y r u   r a i p y   J e s ú s   d e   b n i e t y   n i   c a y u n   s i r v ɨ q u i   :   —   G u l c h a   d e   g u e s q u ɨ   n i s   .   D e n i   b c h a d o o d e b   d e   g u e s q u i   ,  
a x   r a i p y   J e s ú s   l a a d e b   :   —   A n r e   g u l d é e   d u u d x n i   ,   c h i y   g u l c h a d e e d n i   b n i e t y   n i   c a n i á   c a y a c   g a x t q u ɨ   .   Z i y   x q u e l   b a a n d e b   .  
A x   b n i e t y   n i   c a n i á   c a y a c   g a x t q u i   b a a n b ɨ   p r u e b   n i s   n i   g u c t e g a c   v i n   h o r q u i   ,   s i n   q u ɨ t   g á n t i b   c a l í   n e z   z á n i   .   D e   b n i e t t i s y   n i   c a g u i i z n i   n á n   ,   t e   p u r   l a a d e b   g ü e c á a d e b   n i s   .   C h i y r u   b n i e t y   n i   c a n i á   c a y a c   g a x t q u i   g u r ɨ d x b ɨ   b í i n y
a x   r a i p b ɨ   l a a b   :   —   I r a t e   b n i e t y   n i d o o t e   v i n z a a c   r g u i i z d e b   ,   a x   d e n i   a g ü é e d e b   z i i l n i   ,   c h i y r u   r g u i i z d e b   n i   n á   g u l l i a a r u   .   P e r   a n r e   l i ú   g u l u c h u u   v i n z a a c q u ɨ   p a r   i g a a i z n i   a n r u   .  
N i y   n á   n i d o o t e   m i l a g r ɨ   n i   b a a n y   J e s ú s   .   L a a n y   b a a n n y   m i l a g r ɨ q u i   l á a n i   g u ɨ d x   C a n á   n i   n á   n e z   G a l i l e a   .   Z i y   x q u e l   b l i u u n y   g u e l r n a b e e   n i   n a p n y   a x   g ü e l d i l a a z   d e   x p ɨ n n y   l a a n y   .  
C h i   g u d e e d   g u c   z i y   a x   z é g a c n y   g u ɨ d x   C a p e r n a u m   c u n   x n a n n y   c u n   d e   b e t s n y   c u n   d e   x p ɨ n n y   .   R u y   g u z u g u a a d e b   t u b y   t i o p   d x i   .   (   M t   .   2   1   :   1   2   ‑   1   3   ;   M r   .   1   1   :   1   5   ‑   1   8   ;   L c   .   1   9   :   4   5   ‑   4   6   )  
N e   c u n   a b d z ɨ n g a x   p a s c u   ,   l a n í   x t e   d e   b n i e t y   I s r a e l   ,   a x   g ü e   J e s ú s   J e r u s a l é n   .  
C h i y   l o   l d e d o o   J e r u s a l é n q u i   b d x i a l n y   d e   n i   c a t ó o   d e   g ú u n   c u n   d e   l l í i l y   c u n   d e   p a l o m   n e   d e   b ɨ n y   n i   z u b   l o   m ɨ l l y   c a c h a a   x m ɨ l y   d e   b n i e t y   n i   z á   i r ɨ n q u ɨ   n e z   .  
C h i   g u n á   J e s ú s   z i y   a x   b a n c h u u n y   t u b y   c h i c o t y   c u n   d u u   p a r   g u l é e n y   i r a t e   d e   g ú u n   n e   d e   l l í i l y q u i   l o   l d e d o o q u i   n e   b t ɨ ɨ c h n y   x m ɨ l y   d e   b ɨ n y   n i   c a c h a a   m ɨ l y   n e   b z á a l d z a c n y   x m ɨ l l d e b   .  
C h i y   r a i p n y   d e   n i   c a t ó o   p a l o m   :   —   ¡   G u l d é e   d e n g   r u c   !   ¡   Q u ɨ t   r u n n é t   l i z   X t a d a   z e c   l o   g u e e   !  
C h i y r u   g ü e n e l a a z   d e   x p ɨ n n y   l o   x q u i i t s   D i o s   r u t   r n i i   :   “   A x t   g a t i a   q u ɨ t   i s a a n t i a   n i   r g u a l u a a   l i z b i u   .   ”
C h i y   r a i p y   d e   b ɨ n y   I s r a e l   J e s ú s   :   —   ¿ X i   m i l a g r ɨ   i l i u u b i u   d u n n ɨ   p a r   g a c b e e n   d e c   n a p b i u   g u e l r n a b e e   g ú n b i u   z e e c   ?  
A x   c u a b y   J e s ú s   :   —   G u l t s ɨ l y   y u d o o r é   n e   l o   c h o n   d x i z y   a b z u u b a n i   s t u b y   .  
C h i y   r a i p y   d e   b ɨ n y   I s r a e l q u i   l a a n y   :   —   C u a r e n t a   y   s e i s   i z   g u c l d a a d e b   p a r   b z u u b d e b   y u d o o r é   .   N e   l a a b i u   c u n   c h o n   d x i z y l e z y   a b z u u b b i u n i   s t u b y   .  
P e r   J e s ú s   l a g a c q u ɨ   p u r   x c u e r p ɨ n i y   r n i i n y   c h i   r z e e t n y   y u d o o q u i   .  
P u r   n i n g u i   ,   d e n i   g u b á n y   J e s ú s   x t e   n i   g u t y n y   d e   x p ɨ n n y   g ü e n e l a a z d e b   n i   g u n i i n y   ,   a x   g ü e l d i l a a z d e b   x t i i d x n y   n e   g ü e l d i l a a z z a d e b   n i   c á   l o   x q u i i t s   D i o s   .  
L a l z i   n i   g u z u g u a a   J e s ú s   J e r u s a l é n   ,   c h i   l a n í   p a s c u   ,   z i e n y   d e   b n i e t y   g ü e l d i l a a z   l a a n y   c h i   g u n á d e b   d e   m i l a g r ɨ   n i   b a a n n y   .  
P e r   l a a n y   q u ɨ t   g ü e l d i l a a z t i n y   n i   r n i i d e b   t e   p u r   n á n n a c n y   x a   n á   x g a b d e b   .  
Q u ɨ t   r q u i i n t i   t u   g a i p y   l a a n y   x a   n á   b n i e t y   t e   p u r   l a a n y   n a n c h u u n y   x a   n á   x g a b   c a d   t u b y   b n i e t y   .  
G u u   t u b y   b n i e t y   f a r i s e u   n i   b d i a l á   N i c o d e m o   .   L a a b   g u c b ɨ   t u b y   g u r t i s y   l o   d e   b n i e t y   I s r a e l
a x   g ü e t i x l o b   J e s ú s   t u b y   g u x i n   .   C h i y   r a i p b ɨ   l a a n y   :   —   M a i s t r ɨ   ,   d u n n ɨ   n á n n ɨ   d e c   D i o s   b x i a a l d   l a a b i u   p a r   i l i u u b i u   d u n n ɨ   ,   t e   p u r   r u t e e t e   q u ɨ t   t u   c h a l e e t i   g ú n   s a a   d e   m i l a g r ɨ   n i   r u n b i u   b e l a t i   q u ɨ t   r b e z n é b   D i o s   .  
C h i y   r a i p y   J e s ú s   l a a b   :   —   N a r e   r g u i x t e l d í a   l o o   d e c   e l q u ɨ   n i   q u ɨ t   i b í i   g a l   s t u b y   ,   q u ɨ t   x o   i n i á t i b   g u e l r n a b e e   x t e   D i o s   .  
A x   r a i p y   N i c o d e m o   l a a n y   :   —   P e r   ,   ¿ x ó l e s a   i b í i   g a l   b n i e t r o o   s t u b y   ?   ¿ T a t i x   z e l e e   y a i c q u i b ɨ   p a r   i t s ɨ n y   x n a n b ɨ   l a a b   g u ɨ c h l i u   s t u b y   ?  
J e s ú s   c u a i b n y   :   —   N a r e   r g u i x t e l d í a   l o o   d e c   e l q u ɨ   n i   q u ɨ t   r r u b n i s   n e   n i   q u ɨ t   r b e z n é   S p í r i t u   S a n t   q u ɨ t   x o   y i i u t i b   l o   g u e l r n a b e e   x t e   D i o s   .  
D e   b n i e t y   n i   n a b á n y   z e c   n i   n á   x g a b n i   ,   l o   g u ɨ c h l i u t i s y   n a p d e b   g u e l n a b á n y   .   P e r   d e   b n i e t y   n i   r b e z n é   S p í r i t u   S a n t   p u r   S p í r i t u   S a n t   n a p d e b   s t u b y   g u e l n a b á n y   .  
Q u ɨ t   r z a c a n u   p u r   n i   r n i i a   l i ú   :   “   I r a t e   b n i e t y   g u ɨ c h l i u   n á   p a r   c u e z n é   S p í r i t u   S a n t   .   ”
T e   z e c q u ɨ   n i   r b í i   b i   i r a n e z t e   n e   m a s q u ɨ   r i n d i a g u   c h i   r b í i   b i   ,   p e r   n i c   r s o n u   c a l í   n e z   z é e d n i   o   c a l í   n e z   c h i a n i   .   Z i y g a c z a q u ɨ y   n á   S p í r i t u   S a n t   p a r   c u n   i r a t e   d e   b n i e t y   n i   r b e z n é n y   .  
C h i y r u   r a i p y   N i c o d e m o q u i   l a a n y   :   —   P e r   ,   ¿ t a t i x   z i y   r a c   ?  
J e s ú s   c u a i b n y   :   —   ¡   M a i s t r ɨ l e s a   n o o   l o   d e   b n i e t y   I s r a e l   ,   n e   q u ɨ t   g a n n u   d e   c o s q u ɨ   !  
N a r e   r g u i x t i i a   l o o   d e c   d u n n ɨ   r d x u e e n   n i   n á n n ɨ   n e   n i   a g u n á n   .   P e r   l a a t   q u ɨ t   r e l d i l a a z t i t   n i   r n i i n   .  
B e l a t i   q u ɨ t   r e l d i l a a z t ɨ   c h i   r u e n í a   l a a t   d i i d x   p u r   d e   c o s   x t e   l o   g u ɨ c h l i u r é   ,   ¿ x ó l e s a   c h a l d i l a a z t ɨ   c h i   r u e n í a   l a a t   p u r   d e   c o s   x t e   l l a y a b a a   ?  
’ R u t e e t e   g a d y   t u   c h i a t i   l l a y a b a a   s i n o   q u e   t u b y z i   n i   b i a t   d e s d e   l l a y a b a a   n e   l a a n i y   B n i e t y   n i   b x i a a l d   D i o s   .  
N e   z e c   n i   b c u a a   M o i s é s   t u b y   b é e l d   g u i i b   q u i a   y a g   n e z   l o   y i u b i z   ,   z i y t i z i a c z a   B n i e t y   n i   b x i a a l d   D i o s   s c u a a d e b n y   l o   c r u z y   ,  
t e   p a r   i r a t e   d e   n i   c h a l d i l a a z   l a a n y   q u ɨ t   i n i t t i d e b   l o   D i o s   s i n o   q u e   z a p d e b   g u e l n a b á n y   p a r   c h a z y   c u n   l a a n y   .  
’ N e   d e   t a n t   n i   r c a a z   D i o s   b n i e t y   g u ɨ c h l i u   a x   m a s q u ɨ   t u b y z i   L l i i n n y   ,   p e r   b x i a a l d n y   L l i i n n y   t e   p a r   i r a t e   n i   c h a l d i l a a z   l a a n y   q u ɨ t   i n i t t i d e b   l o   D i o s   s i n o   q u e   g a p d e b   g u e l n a b á n y   p a r   c h a z y   n e z   l o n y   .  
T e   p u r   D i o s   q u ɨ t   b x i a a l d t i n y   L l i i n n y   l o   g u ɨ c h l i u   p a r   i s i á l d n y   c a s t i g u   d e   b n i e t y   s i n o   q u e   p u r   l a a n y   g a p   d e   b n i e t y   p e r d ó n   l o   D i o s   .  
’ E l q u ɨ   n i   r e l d i l a a z   L l i i n   D i o s   ,   q u ɨ t   r i á l d t i b   c a s t i g u   x t e   D i o s   .   P e r   e l q u ɨ   n i   q u ɨ t   r e l d i l a a z   ,   l a a b   a r i á l d b ɨ   c a s t i g u   p u r   n i   q u ɨ t   r e l d i l a a z b ɨ   L l i i n   D i o s   n e   t u b y z i n y   n á n y   L l i i n   D i o s   .  
D e   n i   q u ɨ t   r e l d i l a a z   a r i á l d d e b   c a s t i g u   t e   p u r   c h i   b e e d n y   ,   l a a n y   n i   n á n y   b i e e n y   x t e   D i o s   ,   l a a d e b   m a z r u   b d x u l a a z d e b   n e z   m a l   p u r   n i   r u n d e b   p ú r z i   n i   n á   m a l   .  
I r a t e   d e   n i   r u n   n i   n á   m a l   ,   x í t e e t e   r d x a l a a z t i d e b   b i e e n q u i   a x   q u ɨ t   r b i n u u t i d e b n y   p a r   q u ɨ t   y í a n y   x i   m a l   c a y u n d e b   .  
P e r   d e   b n i e t y   n i   n a b á n y   z e c   n i   r i á l d   n e z   l o   D i o s   ,   l a a d e b   z e n u u d e b   b i e e n y   x t e n n y   p a r   y í a n y   d e c   i r a t e   n i   c a y u n d e b   n á   p u r   D i o s   .  
C h i   g u d e e d   g u c   z i y   ,   J e s ú s   c u n   d e   x p ɨ n n y   g ü e d e b   n e z   J u d e a   .   R u y   g u z u g u a n é n y   l a a d e b   t u b y   t i o p   d x i   a x   b t i u b n i s   d e   x p ɨ n n y   d e   b n i e t y   .  
C h i y   z i y z a   g u ɨ d x   n i   l á   E n ó n   n i   n á   g a x   n e z   S a l i m   ,   J u a n y   B a u t i s t   c a t i u b n i s z a c b ɨ   d e   b n i e t y   p u r   n i   n u u   z i i l y   n i s   n e z q u i   a x   r e   d e   b n i e t y   p a r   r r u b n i s d e b   .  
N i y   g u c q u ɨ y   a n s t e   n i   g u i a g u   J u a n y   B a u t i s t   .  
P e r   t u b y   t i o p   d e   x p ɨ n y   J u a n y   c u n   t u b y   t i o p   d e   n i   z e n u u p a c   l e y   g u z u l o   r c h a a d e b   l o   d i i d x   p u r   x c o s t u m b r ɨ d e b   x a   x q u e l   g a c n i a d e b   .  
C h i y r u   g ü e g a t s d e b   J u a n y   :   —   M a i s t r ɨ   ,   c a u r i e n b i u   d e c   b n i e t y   n i   g u z u g u a n é b i u   d e t s   g u e e u   J o r d á n   n i   b e n é b i u   d u n n ɨ   x t i i d x n i   ,   a n r e   a c a t i u b n i s b ɨ   d e   b n i e t y   n e   i r a t e d e b   a z e n u u   l a a b   .  
C h i y   r a i p y   J u a n y   l a a d e b   :   —   R u t e e t e   q u ɨ t   t u   c h a l e e t i   g a p   g u e l r n a b e e   b e l a t i   D i o s   q u ɨ t   i d e e d n i   .  
L a a t   n a n l d í t   d e c   b i n d i a g t ɨ   g u n i i a   g a t i   n a r e t i a   n a a   C r i s t   s i n o   q u e   n a r e   z e l d t i z i a   p a r   z e d t i x t e e g a   p u r   l a a n y   .  
D u n n ɨ   n á n n ɨ   d e c   r u t   r a c   t u b y   s a a   ,   b í i n y   n á   n i   z u g u a n é   d x a a p   .   N e   x m i g u   b í i n y   n i   z u g u a n é   l a a b   h o r q u i   ,   q u e s e n t i a n d   r z a c l a a z b ɨ   c h i   r i n d i a g b ɨ   s u l o   i n i i   b í i n y   d i i d x   .   A n r e   z i y z a q u ɨ y   q u e s e n t i a n d   r z a c l a a z a   p u r   l a a n y   ,  
n e   l a a n y   z e l a a r u p a c   g a c n y   n i   m a z r u   s a c   .   N a r e   a x   z e l a a r u p a c   g a c a   g u l l i a a r u   q u e   l a a n y   p u r   n i   m a z r u   s a c n y   .  
T e   p u r   n i   z é e d   d e s d e   l l a y a b a a   ,   l a a n y   n á   n i   r n a b e e n y   l o   i r a t e   .   P e r   b ɨ n g u ɨ c h l i u   ,   b ɨ n g u ɨ c h l i u t i s y   l a a b   n e   p ú r z i   n i   n u u   l o   g u ɨ c h l i u   r z e e t b ɨ   .   P e r   n i   z é e d   d e s d ɨ   l l a y a b a a   l a a n y   n á   n i   r n a b e e n y   i r a t e
a x   r u e e n y   n i   a g u n á n y   n e   n i   a b i n d i a g n y   .   P e r   r u t e e t e   q u ɨ t   r e l d i l a a z t i   n i   r n i i n y   .  
B e l a t i   n u u   n i   r e l d i l a a z   x t i i d x n y   ,   n i y   z e l o   d e c   p ú r z i   d i d x l d í   n á   x t i i d x   D i o s   .  
N e   e l q u ɨ   n i   z é e d   p u r   D i o s   ,   l a a n y   r u e e n y   x t i i d x   D i o s   p u r   n i   b i a l o   b d e e d   D i o s   l a a n y   g u e l r n a b e e   p u r   S p í r i t u   S a n t   .  
D i o s   r c a a z n y   L l i i n n y   a x   b s á a n n y   i r a t e   l a z n a a n y   .  
N e   t u t i x   n i   r e l d i l a a z   L l i i n n y   ,   l a a b   n a p b ɨ   g u e l n a b á n y   p a r   c h a z y   n e z   l o   D i o s   .   P e r   e l q u ɨ   n i   q u ɨ t   r e l d i l a a z   L l i i n n y   ,   q u ɨ t   x o   g a p t i b   g u e l n a b á n y q u i   s i n o   q u e   l a a b   r i á l d b ɨ   c a s t i g u   x t e   D i o s   .  
D e   f a r i s e u   g u c b e e d e b   d e c   m a z r u   z i e n y   x p ɨ n y   J e s ú s   n e   m a z r u z a   c a t i u b n i s n y   d e   b n i e t y   q u e   J u a n y   ,  
(   m a s q u ɨ   n i   n á p a c n i   g a t i   J e s ú s t i   r t i u b n i s   b n i e t y   s i n o   q u e   d e   x p ɨ n n y   )   .  
N e   p u r   n i   g u c b e e d e b   z i y   n i n g u i   a x   b d i i a   J e s ú s   n e z   J u d e a   p a r   z é n y   n e z   G a l i l e a   s t u b y   .  
P e r   c h i   z é n y   n e z   G a l i l e a   n a p n y   q u e   g u d e e d n y   n e z   S a m a r i a   .  
A x   b d z ɨ n n y   t u b y   g u ɨ d x   x t e   S a m a r i a   r u t   l á   S i c a r   ,   g a x   l o   l i u   n i   b g u a a d   t o   J a c o b   l l i n g a a n b ɨ   t o   G u s é   .  
R u y   n á   b z i a   n i   r n i i d e b   ,   b z i a   x t e   J a c o b   .   N e   c u n   J e s ú s   a b d x a n y   c a z a n y   a x   g u r i n y   r u u   b z i a q u i   z é e d t i   g a c   l a i d x i   .  
C h i y   d e   x p ɨ n n y   g ü e d e b   l á a n i   g u ɨ d x q u i   p a r   g ü e s i i d e b   n i   i q u i i n d e b   .  
H o r q u i   a x   b d z ɨ n y   t u b y   g u n a a   S a m a r i a   r u u   b z i a q u i   z e l d e e b   n i s   ,   a x   r a i p y   J e s ú s   l a a b   :   —   B g u a a d   n a r e   d u u d x   n i s   .  
P e r   c u n   d e   b n i e t y   I s r a e l   q u ɨ t   r c h a a t i d e b   d e   b n i e t y   S a m a r i a   ,   a x   c u a b y   g u n a a q u i   l o n y   :   —   B ɨ n y   S a m a r i a   n a r e   n e   ,   ¿ x í l e s a n i   r n a a b b i u   n i s   l u a a   n e   b n i e t y   I s r a e l   l a a b i u   ?  
C h i y   r a i p y   J e s ú s   l a a b   :   —   B e l r u l a t i   r a c b i i u   n i   r c a a z   D i o s   i n ɨ ɨ d x n y   l i ú   ,   n e   b e l r u l a t i   r a c b i i u   t ú   c a n a a b   n i s   l i ú   ,   l i ú   s n a a b u   n i s   n a r e   n e   n a r e   s n ɨ ɨ d x a   l i ú   n i s   n i   r g u a a d   g u e l n a b á n y   .  
C h i y r u   r a i p y   g u n a a q u i   J e s ú s   :   —   D a d   ,   n i c l ɨ   q u ɨ t   x i   c a a b i u   p a r   c u é e b i u   n i s   ,   n e   b z i a c   q u e s e n t i a n d   g u é t n i   .   ¿ C a l í l e s a   c h a c á a b i u   n i s   n i   r g u a a d   g u e l n a b á n y   ?  
B z i a c   d e s d ɨ   t o   x p ɨ n g u l n ɨ   J a c o b   b s a n n é n y   d u n n ɨ   ,   n e   l a g a c   n i s q u ɨ   b q u i i n b ɨ   z i y z a   d e   l l i i n b ɨ   c u n   d e   l a d x a a   x t e n d e b   .   A n r e   ,   ¿ t a t i x   m a z r u   s a c b i u   q u e   l a a b   ?  
C h i y   r a i p y   J e s ú s   l a a b   :   —   I r a t e   d e   n i   r é e   n i s q u ɨ   r d x á g a c d e b n i   s t u b y   .  
P e r   e l q u ɨ   n i   g u é e   n i s   n i   i d e e d a   ,   q u ɨ t r u   c h ú u t i   d x i   i d x á b n i   .   T e   p u r   n i s   n i   i d e e d a b   z a c n i   n e z   l á a n b ɨ   z e c   t u b y   r u t   q u ɨ t   r b e z t i   r a c h y   n i s   ,   a x   a n a p b ɨ   g u e l n a b á n y   p a r   c h a z y   .  
C h i y r u   r a i p y   g u n a a q u i   l a a n y   :   —   D a d   ,   b g u a a d b i u   n a r e   n i s q u i   p a r   q u ɨ t r u   i b í i t i   i d x a a   n i s   ,   n i c l ɨ z a   q u ɨ t r u   g u e d l d é e t i a n i   r u c   .  
J e s ú s   r a i p y   l a a b   :   —   Q u e g ü e t ɨ d x   c h i a l u   ,   c h i y r u   g u e e d u   .  
G u n a a q u i   a x   c u a i b b ɨ   :   —   Q u ɨ t t i   c h i a l a   .   C h i y r u   r a i p y   J e s ú s   l a a b   :   —   G u l d í c u   q u ɨ t t i   c h i a l u
t e   p u r   a g u c   g a a y   c h i a l u   r u u   ,   n e   a n r e   b n i e t y   n i   r b e z n í u   n i c l ɨ   g a t i   c h i a l u   r a c b ɨ   .   P u r   n i n g u i   ,   d i d x l d í c   n á   n i   r n i i u   .  
C h i   b i n d i a g   g u n a a q u i   z i y   ,   a x   r a i p b ɨ   l a a n y   :   —   D a d   ,   r d x a l u a a   d e c   l a a b i u   n á b i u   t u b y   p r o f e t   x t e   D i o s   .  
D e   t o   x p ɨ n g u l   g u l a l n ɨ   q u i a   d a n y q u ɨ   b t o d e b   D i o s   ,   p e r   l a a t   n i   n á t   b n i e t y   I s r a e l   r n i i t   d e c   J e r u s a l é n   n á   p a r   i t o n   D i o s   .  
J e s ú s   a x   c u a i b n y   :   —   G u n a a   ,   g ü e l d i l a a z   n a r e   d e c   t e r u   i d z ɨ n y   d x i   n i   i t o t   X t a d n ɨ   D i o s   s i n   q u ɨ t   g u e e d t i t   n i c l ɨ   q u i a   d a n y q u ɨ   n i c l ɨ z a   J e r u s a l é n   .  
L a a t   n i c l ɨ   q u ɨ t   g á n t ɨ   t ú   r t o t   .   P e r   d u n n ɨ   n a n c h u u n   t ú   r t o n   t e   p u r   l o   d e   b n i e t y   I s r a e l   z á   n i   g ú n   p e r d ó n   b n i e t y   .  
N e   a n a c r e   a b d z ɨ n y   d x i   n i   i r a t e   d e   n i   g u l d í p a c   r t o   D i o s   ,   s t o d e b n y   z e c   n i   r i á l d   p u r   S p í r i t u   S a n t   x t e n n y   .   T e   p u r   z i y   r c a a z   X t a d n ɨ   D i o s   g ú n   d e   n i   r t o   l a a n y   .  
D i o s   n á   S p í r i t   n e   d e   n i   r t o   l a a n y   n á   p a r   i t o d e b n y   d i b y q u i a   d i b y l a a z d e b   p u r   S p í r i t u   S a n t   .  
C h i y r u   r a i p y   g u n a a q u i   J e s ú s   :   —   N a r e   n á n n a   d e c   n á   p a r   g u e e d   M e s í a s   n i   l á z a   C r i s t   .   N e   c h i   g u e e d n y   l a a n y   q u i x t e e n y   l o n   i r a t e   .  
J e s ú s   r a i p y   l a a b   :   —   N a r e n i y   C r i s t   n i   r z e e t u   ,   l a a n i y   c a n i n é n y   l i ú   .  
H o r q u i   a x   b d z ɨ n y   d e   x p ɨ n n y   n e   b d x a l o d e b   p u r   n i   c a y u e n é n y   t u b y   g u n a a   d i i d x   .   P e r   n i c   t u b y d e b   q u ɨ t   n i n a b d i i d x t i   l a a n y   x i   r c a a z   g u n a a q u i   ,   o   x i y   c a y u e e d e b   .  
C h i y   g u n a a q u i   b s á a n a c b ɨ   r i i   x t e n b ɨ   r u u   b z i a q u i   ,   a x   z é g a c b ɨ   l á a n i   g u ɨ d x   r u t   g ü e g a t s b ɨ   d e   b n i e t y   :  
—   G u l t a g u i a a   t u b y   b n i e t y   n i   a g u n i i   n a a   i r a t e   n i   a b a a n i a   .   ¿ L a d x a   g a t i   l a a b ɨ y   C r i s t   ?  
C h i y r u   b d i i a d e b   l á a n i   g u ɨ d x q u i   p a r   g ü e d e b   r u t   z u g u a a   J e s ú s   .  
P e r   l a l z i   n i   z é   g u n a a q u i   l á a n i   g u ɨ d x q u i   ,   d e   x p ɨ n y   J e s ú s   r a i p d e b   l a a n y   :   —   M a i s t r ɨ   ,   b q u i i n b i u   .  
P e r   l a a n y   r a i p n y   l a a d e b   :   —   N a r e   a   n i   i q u i i n i a   r á p a   ,   p e r   q u ɨ t   g á n t i t   x a   n á n i   .  
A x   g u z u l o   r n a b d i d x s a a   d e   x p ɨ n n y   :   —   ¿ L a d x a   n u u   n i   b d e e d   x i   b q u i i n n y   ?  
C h i y r u   r a i p y   J e s ú s   l a a d e b   :   —   G u e l r q u i i n y   x t e n a   n á   g ú n a   z e c   n i   r c a a z   D i o s   n i   b x i a a l d   n a r e   ,   n e   y a l o z a   g ú n a   n i   g u n i i n y   g ú n a   .  
L a a t   r n i i t   :   “   R i e e d x   s t a p   b ú i u   p a r   s u l o   g a c   d e   c o s e c h   .   ”   P e r   n a r e   r n i i a   l a a t   :   G u l d i a s l o   ,   g u l g u i a a   l o   d e   y á a n   a g u l d   i d o p n i   .  
N e   b n i e t y   n i   r t o p n i   ,   r c á a b   n i   r i á l d b ɨ   p u r   d z ɨ ɨ n y   n i   r u n b ɨ   .   C h i y   d e   c o s e c h   n i   r t o p b ɨ   a   n á   p a r   r u t   n u u   g u e l n a b á n y   p a r   c h a z y   .   Z i y   x q u e l   a x   z e c l ɨ   n i   r z i b i n n i   n e   z e c l ɨ z a   n i   r t o p n i   t u b y l o t e   r z a c l a a z d e b   .  
D i d x l d í q u ɨ y   n i   r n i i   b n i e t y   :   “   I r ɨ n y   n i   r u n   d z ɨ ɨ n y   c h i y   i r ɨ n y   n i   r t o p   d e   g u e l n a z a a c   .   ”
N a r e   b x i a a l d a   l a a t   p a r   c h a t o p t ɨ   d e   g u e l n a z a a c   r u t   n i c l ɨ   q u ɨ t   b a a n t i t   d z ɨ ɨ n y   .   I r ɨ n q u ɨ   d e   n i   b a a n y   d z ɨ ɨ n y   ,   c h i y   l a a t   g ü e t o p   ,   g ü e t o p z i t   d e   g u e l n a z a a c   r u t   b a a n d e b   d z ɨ ɨ n y   .  
Z i e n y   d e   b n i e t y   S a m a r i a q u i   g ü e l d i l a a z   J e s ú s   p u r   x t i i d x   g u n a a q u i   ,   c h i   r a i p b ɨ   l a a d e b   :   “   A g u n i i n y   n a r e   i r a t e   n i   a b a a n i a   .   ”
P u r   n i n g u i   ,   c h i   b d z ɨ n y   d e   b n i e t y   S a m a r i a q u i   r u t   z u g u a a   J e s ú s   a x   b a n l a s d e b   l o n y   p a r   s u g u a n é n y   l a a d e b   .   C h i y   g u z u g u a n é n y   l a a d e b   t i o p   d x i   .  
N e   m a z r u   z i e n d e b   g ü e l d i l a a z   l a a n y   c h i   b i n d i a g d e b   n i   r n i i n y   .  
C h i y r u   r a i p d e b   g u n a a q u i   :   —   A n r e   a g a t i   p u r z í t i   n i   g u n i i u   d u n n ɨ   r o l d i l a a z n ɨ n y   s i n o   q u e   p u r   n i   l a g a c   d u n n ɨ   a b i n d i a g n ɨ   n i   r n i i n y   .   N e   n a n l d í n   d e c   l a a n i y   C r i s t   n i   r u n   p e r d ó n   b n i e t y   g u ɨ c h l i u   .  
C h i   g u d e e d   t i o p   d x i q u i   ,   J e s ú s   b d i i a n y   n e z   S a m a r i a   a x   g ü e l a a r u   z é n y   n e z   G a l i l e a   .  
M a s q u ɨ   l a g a c   l a a n y   g u n i i n y   d e c   n i c   t u b y   p r o f e t   n i   r n i i   x t i i d x   D i o s   q u ɨ t   r á p t i d e b   d i d x d o o   l a a b   l a d x b ɨ   ,  
p e r   c h i   b d z ɨ n n y   n e z   G a l i l e a   ,   d e   b n i e t y   n e z q u i   g ü e n q u ɨ   b a a n d e b   r e c i b i r n y   .   T e   p u r   g ü é z a d e b   l a n í   p a s c u   J e r u s a l é n   a x   g u n á d e b   i r a t e   n i   b a a n n y   l o   l a n í q u i   .  
C h i y r u   g u b í i   b i e c q u i   J e s ú s   C a n á   t u b y   g u ɨ d x   x t e   G a l i l e a   ,   r u t   b a a n n y   g u c t e g a c   n i s   v i n   .   N e   g u ɨ d x   C a p e r n a u m   g u u   t u b y   x p ɨ n y   r e y   n i   r a c x ú   t u b y   l l i i n n i   .  
C h i   g u c b e e   x p ɨ n y   r e y q u i   d e c   a b d z ɨ n y   J e s ú s   n e z   G a l i l e a   x t e   n i   b z a n y   n e z   J u d e a   ,   a x   g ü e b   r u t   b d z ɨ n n y   n e   b a n l a s b ɨ   l o n y   p a r   c h a s i a c n y   l l i n g a a n b ɨ   n i   a p a c m e r   g a t y   .  
A x   r a i p y   J e s ú s   l a a b   :   —   L a a t   a x t   b e l   q u ɨ t   i n i á t   x i   d e   s e n y   o   d e   m i l a g r ɨ z a   ,   q u ɨ t   c h a l d i l a a z t ɨ   .  
P e r   x p ɨ n y   r e y q u i   c u a i b b ɨ   :   —   D a d   ,   g u e e l d z i   q u e d a a b i u   a n s t e   g a t y   l l i n g a a n a   .  
C h i y r u   r a i p y   J e s ú s   l a a b   :   —   Q u e b i e c q u i   l i z u   .   A   l l i n g a a n u   a n u z a a c   .   B n i e t q u i   g ü e l d i l a a z b ɨ   x t i i d x   J e s ú s   a x   z í a g a c b ɨ   l i z b ɨ   .  
C h i y   l a l z i   n i   z í a b   a x   g ü e c h a l o   d e   x m o s b ɨ   l a a b   ,   r a i p d e b   l a a b   :   —   A   l l i n g a a n b i u   a n u z a a c   .  
C h i y   g u n a b d i i d x b ɨ   l a a d e b   x o r t i   g u z u l o   r u z a a c   l l i i n b ɨ   ,   a x   r a i p d e b   l a a b   :   —   N a y   z e c t i   r c a   t u b y   g u d x i   g u b i c á   x l i a a q u i   .  
C h i y r u   b i a b   b n i e t q u i   c u e n d   d e c   h ó r a c q u i y   r a i p y   J e s ú s   l a a b   :   “   A   l l i n g a a n u   a n u z a a c   .   ”   A x   l a a b   n e   i r a t e   d e   x f a m i l b ɨ   g ü e l d i l a a z d e b   J e s ú s   .  
N i y   g u c   n i   r r o p   m i l a g r ɨ   n i   b a a n y   J e s ú s   n e z   G a l i l e a   c h i   b z a n y   n e z   J u d e a   .  
